actionhero/actionhero

bin/methods/generate.js, bin/templates/plugins.js, config/api.js, config/plugins.js, test/actions/cacheTest.js
Hi Evan
Here's my PR WRT https://github.com/evantahler/actionhero/issues/512. It's a branch obviously, I thought that'd likely be best but I can merge into `master` if you prefer.
I hope i've done the right thing but please let me know if you don't think I have. It's tricky to test without being able to install via NPM but from what I can see, the plugins are loading correctly.
I wasn't sure whether to add to `package.json` `install` string or not but this PR includes the option for an argument on the `generate` method to add plugins to the new `config/plugins.js` file. The arg is `--plugins` and just uses the existing `binary.argv` object. My thinking is that this doesn't break any existing script people may be using and does not add plugins by default but does allow programmatic …
=> Separate plugin config file

client/actionheroClient.js, config/api.js, config/errors.js, initializers/chatRoom.js, test/core/actionCluster.js, test/servers/socket.js, test/servers/websocket.js
This PR updates the chat sub-system in some major ways:
- Added a new type of chat middleware, `sayCallbacks`.  This allows you to modify messages being sent to clients, log all messages your self, etc.  It is similar in nature to the `joinCallbacks` and  `leaveCallbacks`.
- All chat callbacks now process serially.  
- All chat callbacks now require a callback as the final argument:
```javascript
var chatMiddlewareToAnnounceNewMembers = function(connection, room, callback){
api.chatRoom.broadcast({}, room, 'I have entered the room: ' + connection.id, function(e){
callback();
});
}
api.chatRoom.addJoinCallback(chatMiddlewareToAnnounceNewMembers, 100);
var chatMiddlewareToAnnounceGoneMembers = function(connection, room, callback){
api.chatRoom.broadcast({}, room, 'I have left the room: ' + …
```
=> Chat Callbacks

initializers/configLoader.js
This PR allows the use of multiple config paths. A typical use-case would be to provide default config settings in a project, with "local" settings that apply only to a specific server. This makes it easy to keep database passwords, API keys, and other security-sensitive information out of your repository, or to adjust server-specific settings such as which nodes will run background tasks vs. Web services.
This change preserves the existing load order for ActionHero configs:
1. The project's 'config' folder, if exists
1. `actionhero --config=PATH` parameters. More than one --config value may now be provided.
1. `ACTIONHERO_CONFIG=PATH npm start` style environment variables.
In addition, config paths may include more than one path, separated by commas. This is handy when using the …
=> Allow the use of multiple config specifications.

actions/cacheTest.js, actions/randomNumber.js, actions/showDocumentation.js, actions/sleepTest.js, actions/status.js, bin/templates/action.js, initializers/actionProcessor.js, initializers/actions.js, initializers/params.js, test/actions/cacheTest.js, test/actions/randomNumber.js, test/actions/showDocumentation.js, test/core/api.js, test/servers/web.js
This PR allows us to finally provide `defaults`, `validation`, `formatting`, and `requirements` to an action's inputs.  
This is a breaking change.
```javascript
exports.sleepTest = {
name: 'sleepTest',
description: 'I will sleep and then return',
inputs: {
sleepDuration: {
required: true,
formatter: function(n){ return parseInt(n); },
default: function(){ return 1000; }
validator: function(n){
if(n < 1000){ return 'sleepDuration should be longer than 1 second'; }
else{ return true; }
}
}
},
run: function(api, connection, next){
setTimeout(function(){
next(connection, true);
}, connection.params.sleepDuration)
})
}
```
The options are:
- `required` (boolean)
- `formatter = function(param, connection, actionTemplate)`
- will return the new value of the param
- `default = function(param, …
=> param validation

README.md
Running the existing instructions without knowing how the generator works resulted in a mess of new files + directories in my home dir. No big deal, but it is a noob pitfall that could be easily avoided, so I thought I would mention it here.
Another solution would be to add the ability to specify a target directory to the generator tool, e.g. `actionhero generate my_new_project` that would create the `my_new_project` directory if it didn't already exist.
=> Added new directory command to Quick Start section

initializers/actionProcessor.js, test/core/api.js
Modify the reduceParams function of the actionProcessor initializer to allow params from the globalSafeParams array rather than the postVariables array
=> Fix unexpected param filtering behavior - resolves #582

client/actionheroClient.js, package.json
iojs v1.3.0 exposed a bug where (in testing) the AH websocket client lib could have errors with multiple clients.  We were not 'formally' declaring the client as extension of the EventEmmiter, rather just hijacking the prototype.
=> Formal EventEmitter inheritance for AH client

docs/core/actions.md
Add some more docs for action inputs, explicitly showing that they are optional.
=> Add more docs around action inputs

actionhero.js, bin/methods/start.js, config/logger.js, initializers/actions.js, initializers/servers.js, servers/socket.js, servers/web.js
rather than sprinkling `process.exit()` throughout your initializers, it is better to allow all initializer steps (`initializes()`, `start()`, `stop()`) to pass an error callback.  actionhero in turn will stop the process if an error is detected. 
The same logic has been extended to the `start()` methods of servers. 
Also ensured that the exit code of actionhero is `1` when an error occurs.
=> initializers to return errors which will be passed up to the boot process

initializers/routes.js
This moves the actual creation of routes to a single place and exposes a method on `api.routes` called `registerRoute(method, path, action)`.
I'm planning to use the `registerRoute` method to add routes to an application from an initializer (in a plugin), hopefully it's useful elsewhere too :)
=> Refactor route creation and expose api.routes.registerRoute

docs/core/tasks.md
Added documentation for a tasks `next` callback.
Fix `api.tasks.allWorkingOn` docs.
Make examples consistent by removing parameters to `next` callback.
=> Pass through task documentation

config/tasks.js, initializers/resque.js
Trying to reduce the verbosity of resque logging.
=> pushing a number of resque logs deeper

bin/templates/gruntfile.js, bin/templates/initializer.js, bin/templates/server.js, bin/templates/task.js
Noticed that generated components have missing semicolons, so decided to update templates to include them, so at least eslint/jslint/jshint has less stuff to complain about.
=> Clean up templates.

actions/cacheTest.js, actions/randomNumber.js, actions/showDocumentation.js, actions/sleepTest.js, actions/status.js, bin/templates/action.js, initializers/actionProcessor.js, initializers/connections.js, initializers/exceptions.js, initializers/genericServer.js, initializers/specHelper.js, servers/socket.js, servers/web.js, servers/websocket.js, tasks/runAction.js, test/core/api.js, test/core/binary.js, test/core/exceptions.js, test/core/middleware.js, test/servers/socket.js, test/servers/web.js, test/servers/websocket.js
This allows us to remove the notion of `connection._originalConnection` in actions/middleware.  This simplifies the code and allows for expected behavior (modifying `connection` will persist) to occur.
This PR drastically changes the APIs of actions and middleware.  
Action Syntax now looks like this: 
```js
run: function(api, data, next){
data.response.randomNumber = Math.random();
next(error);
}
```
Where data contains:
```
data = {
connection: connection,
action: 'randomNumber',
toProcess: true,
toRender: true,
messageCount: 123,
params: { action: 'randomNumber', apiVersion: 1 },
actionStartTime: 123,
response: {},
}
```
Now, when you run an action, you modify `data.response`.  If there is an error, you callback to `next(err)` with it.
If you don't want to `toRender`, just set it to …
=> [HOLD] Remove Original Connection

client/actionheroClient.js
When the ActionheroClient makes requests over HTTP, it constructs a string to pass as URL parameters to a GET request. As in:
for (var i in params) {
qs += i + '=' + params[i] + '&';
}
This is troublesome for parameter objects such as:
{ a: { b: 3 } }
I've modified the webAction() to stringify and POST the parameter data if it is an object.
Although thinking now, the parameter argument should *always* be an object, making the original GET request code unnecessary if the new POST code is preferred.
=> Complex objects as ActionheroClient's webAction() parameters

initializers/routes.js, test/servers/web.js
Hey,
currently there is no way to add a route (e.g `POST /old_login`) which will target a specific version of an action. The only way to achieve this is to add `?apiVersion=x` to the request, which is problematic if you have for example some legacy mobile apps which can't be updated.
I've added the possibility to define default params for every route:
```js
post:{
{ path: '/old_login', action: 'login', params:{ apiVersion: '1' } }
}
```
this will also work for other params beside `apiVersion`.
Tests are included!
=> add default params to routes

initializers/stats.js
live reload caused writeIncrements to create new timers before clearing the old timer
=> stats memory leak

docs/core/chat.md
1. There are two roomStatus references in here, but the first one is only partially written.
1. The say() middleware callback requires a parameter (the message). If not passed into the callback, say() never sends anything.
=> Fix unclear chat documentation for latest API

config/api.js, initializers/connections.js
Make it optional that each new connection has a `remotePort` and `remoteIp`
=> Optionally Enforce connection properties

learn-more/index.html
Since you're not doing a hard compare with null it's more javascripty to just check if `err` is truthy.
=> Slight JS Example Improvment

client/actionheroClient.js
Rather than reuse an existing primus transport, we should create a new one.  This will help solve double-callbacks and double-emits which would otherwise be confusing
=> when manually reconnecting to ws, destroy and create a new primus transport

package.json
node-uuid 1.4.6 just came out and looks like they nuked 1.4.4. Needs a relative semver rather than a hard-coded one.
Probably true for the others as well...
=> Change node-uuid to a relative dependency

package.json
This changes the package requirements to compatible-with deps instead of hard-coded version numbers. Hopefully this will help prevent immediate failures if packages get unpublished in the future, like node-uuid 1.4.3 did.
=> Update requirements to compatible-with

README.md
I've updated the README so that links to the documentation point at the new Slate-based site.
=> Fix broken documentation links

config/tasks.js, initializers/exceptions.js, initializers/resque.js, initializers/tasks.js, site/source/includes/docs/core/tasks.md
See the config file for the user-facing updates to task logging. The verbose option was left intact for scheduler logging, and is used to override the task verbosity. I did this to keep a single option around for quick debugging but I'm open to tweaking this!
This change is backwards-compatible and transparent to extisting configurations and includes documentation updates (Implements #719)
=> Implements task logging verbosity configuration options.

initializers/routes.js, site/source/includes/docs/core/plugins.md, site/source/includes/docs/servers/web.md, test/servers/web.js
Enables a new option, `matchTrailingPathParts` which you can enable in the router to match combination paths: 
```javascript
post: [
// yes match: site.com/api/123
// no match: site.com/api/123/admin
{ path: '/login/:userId(/.*/)', action: 'login' }
],
post: [
// yes match: site.com/api/123
// yes match: site.com/api/123/admin
{ path: '/login/:userId(/.*/)', action: 'login', matchTrailingPathParts: true }
],
```
This also enables "catch all" routes, like: 
```javascript
get: [
{ path: ':path(/.*/)', action: 'catchAll', matchTrailingPathParts: true }
],
```
If you have a route with multiple variables defined and `matchTrailingPathParts` is true, only the final segment will match the trailing sections:
```javascript
get: [
// the route site.com/users/123/should/do/a/thing would become …
```
=> enable `matchTrailingPathParts` in router

bin/actionhero
This pull request fixes the symlink creation on windows.
See https://nodejs.org/api/fs.html#fs_fs_symlink_target_path_type_callback
fs.symlink(target, path[, type], callback)
The type argument can be set to 'dir', 'file', or 'junction' (default is 'file') and is only available on Windows (ignored on other platforms
=> fix symlink creation on windows

initializers/connections.js
Using paramAdd over tcp socket with no arguments throws TypeError
/node_modules/actionhero/initializers/connections.js:200
if(words[0].indexOf('=') >= 0){
^
TypeError: Cannot read property 'indexOf' of undefined
=> fix(initializers): paramAdd with no params raises TypeError

site/source/includes/docs/core/middleware.md, site/source/includes/docs/servers/socket.md
Converted `resposne` to `response` and `apiResposne` to `apiResponse`. My text editor also automatically removed some unnecessary spaces at the end of lines. Hopefully that's fine.
=> Fixed some typos in docs.

initializers/staticFile.js, site/README.md, test/servers/web.js
[HOTFIX] - When linking plugins with public directories, their `/public` directories should be sourced by the static file server.  
We should not modify `api.config.general.paths.public` to do this.
=> serve static files from linked plugins

initializers/redis.js
Older actionhero installs used redis.package instead of redis.pkg (12.2.0 at least) so this should ensure backwards compatibility.
=> Package keyword issues

client/actionheroClient.js
Referring to #772, will enable to have the `GET` query params inside the url in case of a client action is called using the actionWeb method
ex:
``` javascript
client.action("myActionName", {httpMethod: 'GET', param1: value1, param2: value2}, function (apiResponse) {
console.log(apiResponse)
});
// will result to:
{webApiUrl}/api?action=myActionName&param1=value1&param2=value2
```
=> #772 - Using the `ActionheroClient.prototype.actionWeb` with GET method

actions/randomNumber.js, initializers/cache.js, site/source/includes/docs/core/cache.md, test/core/cache.js
`api.cache` implements a distributed shared list.  3 simple functions are provided to interact with this list, `push`, `pop`, and `listLength`.  These lists are stored in Redis, and cannot be locked.  That said, a `push` and `pop` operation will guarantee that one-and-only-one copy of your data is returned to whichever application acted first (when popping) or an error will be returned (when pushing).
* Invoke: `api.cache.push(key, data, next)`
* data must be serializable via JSON.stringify
* Callback: `next(error)`
* Invoke: `api.cache.pop(key, next)`
* Callback: `next(error, data)`
* data will be returned in the object form it was saved (array, object, string)
* Invoke: `api.cache.listLength(key, next)`
* Callback: `next(error, length)`
* length will be an integer.
* if the list does …
=> array.cache.list

site/source/includes/docs/core/plugins.md
Running `./node_modules/actionhero link --name nameOfPlugin` results in this error `./node_modules/actionhero: is a directory`... because it's a directory. Added the correct path to the documentation.
=> Fix path of actionhero script in plugin docs

package.json
From node resque: https://github.com/taskrabbit/node-resque/pull/121
**This is a breaking change**
When comparing this project to ruby resque, we had been using the wrong value (key pointer) in the delayed job queue.  When running this project alongside a ruby scheduler, it was possible for older timestamp key set entries not to be deleted.  This update corrects the difference. 
When upgrading to this new version, it is very likely you will end up with queue artifacts that are not properly deleted, which have the potential to break plugin's behaviors.  This will require manual intervention to remove keys that match `resque:timestamps:*`.  Before upgrading to this version, the safest path forward is to drain all of your queues and schedules first, using the previous version of node-resque. …
=> node-resque v2.0.0

bin/methods/start.js, site/source/includes/docs/ops/running_actionhero.md
When the `shutdownTimeout` is reached because actionhero couldn't stop in time, we now throw an error rather than just simply `process.exit(1)`.  This will present the error to stdout properly and be caught as an `uncaughtError` by `actionhero startCluster` to be logged. 
Also docs. 
For @crrobinson14
=> handle stop timeout better + missing docs

servers/web.js, test/servers/web.js
Support /public filenames with encoded spaces in URL. The URL must be properly encoded, for example, note the %20 and +:
http://localhost:8080/sky%20with+space.jpg
=> Support /public filenames with encoded spaces in URL

bin/templates/action.js, bin/templates/initializer.js, bin/templates/server.js, bin/templates/task.js
Nothing major, but saves a hassle of a step if I want to use ES6 or ES7 features in Actionhero.
=> Added "use strict" to templates

.eslintignore, CONTRIBUTING.md, initializers/servers.js, package.json
- now `eslint` dependency makes sense
- it's easy to check style - just run `npm run lint`
- added .eslintignore to not check troublesome scripts (client, templates, site, ...)
A side note - there really was no need for Grunt. Good call removing it.
=> eslint npm script, instructions, and a single style fix

initializers/routes.js, site/source/includes/docs/servers/web.md, test/servers/web.js
now you can check `connection.matchedRoute` to see the details of the route that got the `web` connection to this action... if in case a route was matched.
```js
data.connection.matchedRoute = { 
path: '/mimeTestAction/:key',
matchTrailingPathParts: false,
action: 'mimeTestAction'
}
```
=> expose matched route to connection

config/errors.js, initializers/cache.js, initializers/connections.js, initializers/i18n.js, initializers/logger.js, site/source/includes/docs/core/localization.md, test/core/i18n.js, test/servers/socket.js
No more ugly `api.i18n.i18n...` calls. Added `api.i18n.localize`. 
Also localized some strings in `initializers/cache.js` and `config/errors.js`.
Localizing strings is now really easy. :) I guess documentation has to be changed now.
`api.i18n.localize(message, options)`, first argument is sprintf array it can also accept a string, second argument is optional ( default is api.i18n )
=> I18n rewrite

config/tasks.js, initializers/resque.js, site/source/includes/docs/core/tasks.md
Extending/modifying the current functionality of Resque within ActionHero is currently very cumbersome and has made upgrading our deployments very troublesome. I am proposing adding a configuration section to `config/tasks.js` to allow developers to replace the existing queues, scheduler, and multiWorkers with custom implementations. 
An example extension to queues: 
```javascript
'use strict';
var NR = require('node-resque');
var pluginRunner = require('../node_modules/node-resque/lib/pluginRunner.js');
//noinspection JSUnresolvedVariable
module.exports = {
loadPriority:  590,
initialize: function(api, next){
api.customResque = {};
let customQueue = NR.queue;
customQueue.prototype.enqueueFront = function(q, func, args, callback){
var self = this;
if(arguments.length === 3 && typeof args …
```
=> Bring your own workers

initializers/servers.js
Found that `api.servers.servers` was empty when returning data to the client from an action. Looks like it was defined as an Array but then subsequently is used as an Object.
Changing it to Object allows us to stream results directly from an action to the client, e.g. `api.servers.servers.web.sendFile(connection, error, fileStream, mime, length, lastModified)`.
=> Fixes direct access of servers via api.servers.servers

bin/templates/package.json, config/api.js, config/redis.js, config/tasks.js, initializers/cache.js, initializers/chatRoom.js, initializers/config.js, initializers/redis.js, initializers/resque.js, package.json, site/source/includes/docs/core/action_cluster.md, test/core/actionCluster.js, test/core/binary.js, test/core/cache.js
There are **so many** ways to configure redis these days... handling the config options for all of them (sentinel?  cluster?) is a pain... so lets just let the users configure things directly.  It will be so much simpler!
---
- in `config/redis.js`, you now define the 3 redis connections you need explicitly rather than passing config options around:
```js
var host     = process.env.REDIS_HOST || '127.0.0.1';
var port     = process.env.REDIS_PORT || 6379;
var database = process.env.REDIS_DB   || 0;
exports['default'] = {
redis: function(api){
var Redis = require('ioredis');
return {
'_toExpand': false,
// create the redis clients
client:     Redis.createClient(port, host),
subscriber: Redis.createClient(port, host),
tasks:      Redis.createClient(port, host),
};
}
};
```
- move …
=> Redis client

actions/sleepTest.js, actions/status.js, config/api.js, test/actions/showDocumentation.js, test/core/specHelper.js
load `api.config.general.apiVersion` and `api.config.general.serverName` from the equivalent fields in `package.json`
This is a breaking change.
=> load apiVersion and serverName from package.json

initializers/utils.js
There's a bug in Electron causing directory listing of an ASAR subdirectory to return a listing of the ASAR root, when the path to list has a trailing slash.  To fix:
- remove trailing path separator from `dir` in recursive directory glob
- use path.join(dir, file) instead of path.normalize(dir + file)
=> Electron support, avoid bug electron/electron#5454

config/logger.js
Support for Actionhero installed on a read-only filesystem.
Actionhero checks to ensure its log directory exists by trying to create the log directory.  It does this during config loading.  As a result, when loading the default config it tries to make a log dir inside the node_modules directory.  If that directory is on a read-only filesystem we crash.
One possible solution (presented here) is to delay the directory creation check until after all configs have been loaded.  This way even if Actionhero is installed on a read-only filesystem, the user can provide an alternate log location on a writable filesystem, and we won't try to create any log directories until all configs have been loaded.
=> Delay log directory creation until after configs are loaded

bin/templates/task.js
comment contains '); which seems to be a remnant of some old code, it is out of place now in the comment
=> remove vestigial code fragment from comment

site/source/includes/docs/core/logging.md
api.log was mistyped as api.lot in the documentation that shows up on the docs page on the website
=> fix function name typo

config/errors.js, initializers/actionProcessor.js, site/source/includes/docs/core/actions.md, test/core/api.js
allows for action validators and formatters to use both named methods and direction functions.
```js
exports.cacheTest = {
name: 'cacheTest',
description: 'I will test the internal cache functions of the API',
outputExample: {},
inputs: {
key: {
required: true,
formatter: [
function(s){ return String(s); },
'api.formatter.uniqueKeyName' // <----------- HERE
},
value: {
required: true,
formatter: function(s){ return String(s); },
validator: function(s){
if(s.length < 3){ return '`value` should be at least 3 letters long'; }
else{ return true; }
}
},
},
run: function(api, data, next){
// ...
}
};
```
And then you would define an initializer with your formatter:
```js
'use strict';
module.exports = {
initialize: function(api, next){
api.formatter = {
uniqueKeyName: function(key){
return key …
```
=> Named validators

servers/websocket.js
ActionHero likes to change actionheroClient.js/.min.js so I elected to not track them as they'd be system-specific anyway. This resulted in the javascript folder not existing on other systems, which caused the tests to fail. This is a simple fix to create the javascript folder if it hasn't been.
=> Fix for lack of javascript folder under public

initializers/connections.js, initializers/specHelper.js, test.js, test/core/i18n.js, test/core/specHelper.js, test/servers/socket.js
When creating a new `api.specHelper.connecton()`, the connection should be assigned a fingerprint which is the same as the connection's ID.
=> spec helper should have fingerprint

initializers/tasks.js, site/source/includes/docs/core/middleware.md, test/tasks/middleware.js
It's not needed as there is nothing async here; and this will better match all other addMiddleware signatures.
=> no callback for api.tasks.addMiddleware

actionhero.js, initializers/config.js, initializers/servers.js, site/source/includes/docs/core/development_mode.md
Passing scope into `api.commands.start()`/`stop`/`restart` is dumb.  Lets simplify this! 
Solves https://github.com/evantahler/actionhero/issues/927
=> simply calling of api.commands

config/redis.js
Users with a misconfigured `ioredis` config, or those running Docker containers where the Redis service may not yet be fully started, may see heavy log spam during AH's boot cycle. The default `ioredis` configuration auto-reconnects every 50ms and can rapidly exhaust a log before an admin sees what's going on.
This PR does two things:
1. It provides a staged back-off interval for reconnection attempts up to a maximum, currently set at a low, safe 1 second.
1. It provides a much longer reconnection delay for the FIRST attempt, with a convenience message for the admin:
```
2016-08-23T15:50:41.378Z - notice: * Starting ActionHero *
>> 2016-08-23T15:50:41.389Z - error: Redis connection `client` error Error: connect ECONNREFUSED 127.0.0.1:6379
>>     at Object.exports._errnoException …
```
=> Provide a different initial backoff for ioredis connections that may be misconfigured or not yet available

bin/methods/start/cluster.js
fix a little bug.
I had assigned `.default('workerTitlePrefix', 'actionhero-worker-')`, but look no use.
So I add some code to fix that issue.
=> fix no workerTitlePrefix then show NaN title

initializers/utils.js
I misnamed a plugin reference, and an error had me temporarily confused.
"cannot find linked refrence toah-sequelize.plugin.link "
This fix would format the error as -
"cannot find linked refrence to ah-sequelize.plugin.link"
=> Updates error string formatting

servers/web.js, test/core/staticFile.js
We've found a issue with the etags, every file had the same etag. This was because fileStream.toString() is [object Object] and not the content istself. So every ETAG was generated for [object Object]
I've added a test to check if the ETAG is NOT the same for different files.
=> Fix ETAG issue for files

config/servers/web.js, servers/web.js, site/source/includes/docs/core/file_server.md, test/core/staticFile.js
With this push, no expires or last-modified headers are being sent when etags are enabled. Last-modified and etags are both 'weak' caching headers and we should opt for one; if the developer enabled etags we should make sure they are being used - but atm we let the clients browser implementation decide.
Additionally expires headers won't even be set with etags disabled, as the cache-control header supersedes the 'outdated' expires header - it is replaced by cache-control; both are 'strong' caching headers, we should opt for the newer one, even if it isn't new at all by now.
The current implementation wasn't working right, especially on mobile devices, with files getting cached longer than they should or not at all, depending on the platform.
Caching was a bit of a mess, i refactored the …
=> Fix cache headers

bin/actionhero, bin/methods/version.js, test/core/binary.js
1) add `actionhero version` to return the version of ActionHero being used
2) When using a globally-installed version of actionhero, allow the following subset of commands to be used outside of an ActionHero project directory:
- `actionhero help`
- `actionhero generate`
- `actionhero version`
Other commands will remain crashing outside of an ActionHero project folder, as they will require config files.
=> add `actionhero version` + allow `help` and `version` to be run outside of actionhero projects

servers/web.js, test/servers/web.js
This should resolve the issue for #962. 
I've included a test to reproduce, and within servers/web.js simply moved the if(error) statement above the if-modified-since if statement.
The issue seems to be a 404 file, with a If-Modified-Since header set. I originally thought it might be related to a POST method but it was directly related to the header being set. I just double checked GET and it works as expected. Because of that, in this pull request, you'll see the test using the POST method.
=> Addressing if-modified-since issue on a 404

config/api.js, initializers/staticFile.js
Allow direct configuration of logs when serving files via `api.config.general.fileRequestLogLevel`.  Also show both the file on disk and the requested file path from the URL.
=> configuration setting for logging file requests

config/servers/web.js, docs/_includes/docs/servers/web.html, servers/web.js, test/servers/web.js
ActionHero now allows you to define a collection of host headers which this API server will allow access from.  You can set these via `api.config.servers.web.allowedRequestHosts`.  If the `Host` header of a client does not match one of those listed (protocol counts!), they will be redirected to the first one present.
You can also set `process.env.ALLOWED_HOSTS` which will be parsed as a comma-separated list of Hosts which will set `api.config.servers.web.allowedRequestHosts`
=> HTTP Client Redirection

config/logger.js, initializers/logger.js, test/core/i18n.js
solves https://github.com/evantahler/actionhero/issues/974
Creates a new config option `api.config.logger.localizeLogMessages` which allows developers to opt-into localizing all system log messages (`api.log`).  
The default changes in this pull request from the previous "enabled implicitly" to "disabled explicitly"
=> Do not localize log messages by default; add option to do so

initializers/actionProcessor.js, initializers/specHelper.js, test/core/specHelper.js
If your action returns a `string` or `array`,  and there is an error, we should return the error as a string, and not attempt to return `response.error = error`, as this creates an improper javascript object. 
This extends to the specHelper, whose response types should follow this same pattern.  Actions with string responses will remain as string responses (and arrays).
=> Response type saftey for action errors and spec helper

docs/_includes/docs/deployment/testing.html, initializers/specHelper.js, test/core/specHelper.js
In your tests, if you do not want the `specHelper` actions to include metadata (`data.response.serverInformation`, `data.response.requesterInformation`, and `data.response.messageCount`) from the server, you can configure `api.specHelper.returnMetadata = false` in your tests.</p>
=> api.specHelper.returnMetadata to enable/disable spec helper metadata

initializers/exceptions.js
Remove "uncaught" from error message since the error has actually been caught.
=> Remove "uncaught" from error message

servers/web.js
`chmodSocket` was pulling in external `options` rather than using passed in parameters.
`cleanSocket` and `chmodSocket` both assumed `port` to be a string.  While this _should_ be the case, there are no prior checks for this condition so the error thrown is quite confusing for the end user.  The code has been modified to check that the `port` is a string type before calling `indexOf` on it.
A check of the `port` and `bindIp` attributes should occur somewhere prior to this point and an error thrown.  By default the web test config overrides the `port`, but not the `bindIp`, so an environment configured to use a socket for connections will get an error when running tests unless they know to override the `port` for the test config as well.
=> Fixes socket helper functions

actionhero.js
on ah "stop" the initializers aren't resetted and the duplicate check executes with a false positive
fixes #1006
=> fix issue when ah is restarting

docs/_includes/docs/core/actions.html, initializers/actionProcessor.js, test/core/api.js
Add schema input type for actions:
```
inputs: {
userData: {
required: false,
schema: {
id: {
required: false,
validator: validator('isInt', 'id validate error'),
},
name: {
required: false,
validator: validator('isLength', 'name validate error'),
},
},
},
},
```
=> add schema inputs for Actions

initializers/cache.js, test/core/cache.js
The current implementation of the `cache.lock` method does not check the result of the `setnx` function, which returns either 1 if the key didn't previous exist, and 0 otherwise, this can lead to multiple nodes aquiring the same lock multiple times.
=> Fix cache lock

initializers/connections.js, servers/web.js, test/servers/web.js
This PR proxies the `setHeader` function from a http response object so that actions running on the web server can use `data.connection.setHeader` instead of `data.connection.rawConnection.res.setHeader`.
We also came up with a neat way for servers to apply custom methods to their connections.
Work done with @gcoonrod !
Fixes up https://github.com/actionhero/actionhero/pull/1053
=> server.connectionCustomMethods

initializers/cache.js, initializers/chatRoom.js, initializers/config.js, initializers/resque.js, initializers/specHelper.js, package-lock.json, package.json, servers/websocket.js
Update all packages to the latest versions.
Properly disable `chat`, `cache` and `resque` when `redis` is disabled via config.
Mocha 4.0 has some changes, including that it won't exit the process when the test  suite is done (https://boneskull.com/mocha-v4-nears-release/#mochawontforceexit).  This exposed a few things ActionHero was doing which didn't 'shut down' nicely:
- We were not releasing file change watchers (developer mode) properly when shutting down
- We were not disconnecting the websocket server listeners properly when shutting down
=> Properly release all handlers; Support mocha 4.0

servers/websocket.js, test/servers/websocket.js
When you connect to actionhero via the client over websocket and send 2 parallel requests .... one action request and one "verb" (like 'roomAdd', 'roomLeave' or 'roomView') in the following constellation:
1. send verb roomLeave request
-> connection.messageNumber++ (now 1)
2. send action request (action takes a little longer ~500ms) 
-> connection.messageNumber++ (now 2)
3. answer received from roomLeave request (messageCount send back from actionhero: 2(!!!))
4. answer received fromaction request (messageCount send back from actionhero: 2(!!!))
When the verb is answered, no "messageCount" is given to server.sendMessage ... so the implementation takes the current connection.messageCount number to answer the request.
this pr fixes this problem with creating a temporary variable for the …
=> fix race condition in websocket server

bin/actionhero, bin/methods/generate/plugin.js, bin/methods/help.js, classes/cli.js, config/plugins.js, test/core/cli.js, test/core/plugins.js, test/testPlugin/bin/hello.js, tutorials/plugins.md, tutorials/running-actionhero.md
Solves https://github.com/actionhero/actionhero/issues/1129.
Also allows for `configChanges` to be passed to ActionHero CLI commands via `--configChanges {stringified JSON}` or via ENV.  This is handy when creating tests for CLI commands:
```js
it('can load CLI command from a plugin', async () => {
let env = process.env
env.configChanges = JSON.stringify(configChanges)
let {stdout: helpResponse, stderr: error1} = await promisify(exec)('./bin/actionhero help', {env})
expect(error1).to.equal('')
expect(helpResponse).to.contain('hello')
let {stdout: helloResponse, stderr: error2} = await promisify(exec)('./bin/actionhero hello', {env})
expect(error2).to.equal('')
expect(helloResponse).to.contain('hello')
})
```
Also fixed a a bug where `api.config.general.paths.cli` was not consulted when …
=> Run CLI commands found in plugins `{plugin}/bin` directory

initializers/specHelper.js
This is a fix for problem running unit-tests with non-standard redis configuration. E.g.
```sh
REDIS_HOST=192.168.99.100 npm test -- test/core/tasks.js
```
It tries to reconnect with default redis parameters. See `node-resque/lib/connection`.
=> specHelper redis connection

classes/task.js, initializers/actions.js, initializers/chatRoom.js, initializers/tasks.js, test/core/tasks.js
Update `this` context inside `run` method to the task class instance itself.
It allows to call others task instance methods inside `run`method through `this`.
```js
module.exports = class SomeTask extends ActionHero.Task {
super()
this.name = 'someTask'
this.description = '...'
this.frequency = 0
this.queue = 'default'
this.middleware = []
}
async stepOne (params) {
...
}
async stepTwo (params) {
...
}
async run (params) {
let resOne = await this.stepOne()
let resTwo = await this.stepTwo()
...
}
}
```
=> Fix `this` in tasks

actions/validationTest.js, classes/actionProcessor.js, test/actions/showDocumentation.js, test/actions/validationTest.js
Currently, any param validators that return false do not result in an error response to the action. While the documentation states that a validator should return `true` or an error, having a generic error thrown when `false` is returned results in a slightly more intuitive developer experience.
=> Validators returning false now emit a generic error.

package-lock.json, servers/web.js, test/servers/web.js, tutorials/actions.md, tutorials/web-server.md
A helper for the `web` type of connection to more easily set a custom status code in your actions.  Remember that if you don't want to sent data back to the client, to use `data.toRender = false`:
```js
// actions/custom404.js
const {Action} = require('./../index.js')
module.exports = class Custom404 extends Action {
super()
this.name = 'custom 404 message'
this.description = 'I return a 404 with a sassy message'
this.outputExample = {}
}
async run ({connection, response}) {
response.message = 'nope.'
connection.setStatusCode(404)
}
}
```
=> `connection.setStatusCode` for web clients

classes/actionProcessor.js, test/core/api.js, tutorials/actions.md
Changes the behavior of action's param validators to only mark a param as invalid if they return `false` or throw an error.  Previously, validators which did not return (or returned null) would be marked as failing. 
Solves https://github.com/actionhero/actionhero/issues/1155.
=> action validators which return nothing are valid

classes/server.js, servers/web.js, test/servers/web.js
Found an issue in the action hero web server. If the web server sends a status code 304 response, then the fileStream handle is not closed.
200s are not affected, because their streams get automatically closed by pipe().
=> Issue with unclosed file descriptors

README.md, initializers/config.js
`api.watchedFiles[file].blocked` is an unused artifact from a previous version of ActionHero.  Remove it!
Solves https://github.com/actionhero/actionhero/issues/1162
=> No need for a timer to check file locks in development mode

classes/connection.js, servers/web.js, test/servers/web.js, tutorials/actions.md
solves https://github.com/actionhero/actionhero/issues/1142.
```js
const {Action} = require('actionhero')
module.exports = class StringResponse extends Action {
super()
this.name = 'stringResponse'
this.description = 'I send a string to the client as if it were a file'
}
async run (data) {
data.toRun = false
data.connection.pipe('my response', {'content-type': 'text/plain'})
}
}
```
Adds `connection.pipe(string-or-buffer, headers)` which can be used in your actions for web clients.  This is a helper method which is the same as:
```js
data.connection.setHeader('Content-Type', 'application/xml; charset=utf-8')
data.connection.rawConnection.res.end(fileBuffer)
```
`data.toRender = false` is still needed within the Action's run method.
=> connetion#pipe for web servers sending buffers or strings

initializers/utils.js, test/utils/utils.js
* fix ipv6 parsing for locally scoped URIs
+ added tests for locally scoped URIs
Resolves #1178
=> Fix: Actionhero fails to parse locally scoped IPv6 addresses

classes/actionProcessor.js, config/errors.js, test/core/errors.js, tutorials/actions.md, tutorials/cli.md
As discussed [in Slack channel](https://actionherojs.slack.com/archives/C04EVSUSD/p1518021134000659), Actions that throw an error get a generic hander in `api.config.errors.genericError`. Here the `data.response` could be decorated however needed, like added a `requestId`, or whatever. Default is pure passthrough.
Added the same for a plain `status` that is not an error, just for consistency. Default is passthrough. 
Few tweaks to CLI documentation.
=> generic error decoration hook for action errors, CLI docs cleanup

bin/methods/generate.js, test/core/cli.js
Fixes issue https://github.com/actionhero/actionhero/issues/1188
Copies the root `.gitignore` file into generated projects. 
@evantahler I added the lines as you pointed out - pretty straightforward, thanks for the direction. I added the test and all tests pass; but, I couldn't figure out how to run the generate command locally. I saw the `sample.sh` file in the project root, but running that did not create the `.gitignore` file in the tmp directory - but it looked like maybe that would run from the npm installed version of actionhero instead of my clone of the repository? Any hints on how to do a quick manual check of this functionality using my local repo?
=> Adds gitignore to the copied files list

package.json, servers/web.js, test/servers/web.js
(if this gets accepted, definitely need to `squash` all the commits!)
Quick test can be run with `npm run grepTest "mime"`  (I use that locally in my `package.json`, and can remove if you don't want it in master)
Added processing that awaits for 'end' event from rawBody.
Tests try to simulate what a (slow/actual) network will do for data. If formidable fails, the connection processing finishes **before** the (full) request body is processed. In that case, `rawConnection.params.rawBody` is not available (empty) in middleware or actions. Tests also try to show that normal JSON/formidable processing still works and errors do not hang.
Thoughts on this? There are some comments I will remove, but wanted to check on the approach first.
I used this middleware when processing with my legacy …
=> Capture full rawBody even if formidable fails

__tests__/core/chatRoom.js, bin/deploy-docs, initializers/chatRoom.js
Pointing to issue : #1207 
.forEach built in function does not work properly with async functions. Replaced as per suggestions to use for loop in series.
Updated tests that did not had the async directive on the middleware functions ( causing the tests to pass erroneously ) After putting async directive to wrap up the call in promise, the issue was reproduced.
Then after adding the suggested code with @chimmelb the test pass again and the issue is corrected.
=> Fixed issue #1207. Chat middleware not bubbling up appropriately.

.gitignore, bin/methods/generate.js, bin/templates/gitignore
NPM ignores .gitignore files.
https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package
We'll use a template to generate one for new projects with `actionhero generate`
=> Use a template .gitignore in `actionhero generate`

bin/methods/start/lib/actionheroCluster.js, bin/templates/package.json, config/logger.js, initializers/logger.js, initializers/utils.js, package-lock.json, package.json
Upgrade to winston v3
* moves configuration options for logger into `config/log.js` for explicit customization
* multiple loggers can be defined with unique levels and message formatting options
* ensures `api.config.general.paths.log` paths are created automatically (in initializer rather than config)
* reduces the logic in config file, and makes test env look a lot more like default env
* allows for multiple storage of logs in all directories defined by `api.config.general.paths.log`
This is a breaking change which is mitigated by copying in `config/log.js` from master or a new actionhero project.
=> winston v3

config/servers/web.js
allow uploads >200mb after node-formidable v1.2.1 config update:
https://github.com/felixge/node-formidable/pull/464#issuecomment-374898543
=> added maxFileSize to formOptions

initializers/chatRoom.js
`api.chatRoom.destroy` doesn't wait for each each member to be
removed before destroying the room. This leads to chat room middleware
being run after deletion and bugs can occur if the `leave` middleware
needs to interact with the room before exiting.
Added `await` keyword to the `removeMember`.
=> Wait for chat room members to be removed before destroying room

bin/deploy-docs, initializers/redis.js, package-lock.json
solves https://github.com/actionhero/actionhero/issues/1244
Redis is so fast! Node is so Fast!  It is possible that while `await`ing the write response from redis, that another node got the job and did it already.  If we are waiting for a response, we would miss it!
This PR ensures that there is a response handler/promise before we write to redis, and that we aren't pre-`await`ing it.
=> pre-init doCluster callback before writing to redis

tutorials/plugins.md
Fixing small markdown typo - the link text and URL were reversed.
=> Fixes link to plugin docs

config/servers/web.js
As requested in Slack, adding Strict Transport Security header in the default web http header section.
This means that when a request is made over https, it stores in your browser to always redirect you to the https site for the duration of the max-age even if you type in the http address.
=> Adding strict transport security header as a default in web server config

__tests__/utils/utils.js, initializers/utils.js
As discussed in #1283, the fixed merge behavior, where undefined values are ignored and null values trigger deletion of keys.
Also some more test cases.
=> Config merge empty objects fix, semantic undefined and null

config/tasks.js, initializers/resque.js
Hi,
For some task I need to change namespace for node-resque Queue.Connection. For this I create this PR.
Now this can be done like this:
```
connectionOptions: {
tasks: {
namespace: ['app', 'resque'],
},
```
I can extend the logic to other redis clients(`client`, `subscriber`) if you think it is necessary.
=> Extend resque queue connection options from config

classes/task.js, initializers/tasks.js
Modification of https://github.com/actionhero/actionhero/pull/1309 so that by default periodic tasks with an exception will still be periodically occurring.  The new option, `task.reEnqueuePeriodicTaskIfException` can de set to `false` to have the task stop recurring on an exception.
=> task.reEnqueuePeriodicTaskIfException default  is true

classes/process.js, config/redis.js, initializers/actions.js, initializers/redis.js, initializers/resque.js, initializers/specHelper.js, initializers/tasks.js, servers/websocket.js
Preface:
ActionHero uses the winston syslog loglevels.
The syslog protocol (RFC 5424) knows 8 severities levels:
Code | Level | Description
-- | -- | --
0 | Emergency | system is unusable
1 | Alert | action must be taken immediately
2 | Critical | critical conditions
3 | Error | error conditions
4 | Warning | warning conditions
5 | Notice | normal but significant condition
6 | Informational | informational messages
7 | Debug | debug-level messages
Issue:
I noticed that ActionHero logs some messages with severities worthy of discussion. For example, when I define an error logger in winston, the error log will grow with `*** ActionHero Started ***` and `*** ActionHero Stopped ***` log entries because they are logged with severity `alert`. I think I don't have to take immediate action just …
=> Refactor api.log loglevel severity

__tests__/core/tasks.js, initializers/specHelper.js, tutorials/tasks.md
* Adds `api.specHelper.findEnqueuedTasks` to write tests that check that task was enqueued! 
```js
describe('task testing', () => {
beforeEach(async () => {
await api.resque.queue.connection.redis.flushdb()
})
test('detect that a task was enqueued to run now', async () => {
await api.tasks.enqueue('regularTask', { word: 'testing' })
const found = await api.specHelper.findEnqueuedTasks('regularTask')
expect(found.length).toEqual(1)
expect(found[0].args[0].word).toEqual('testing')
expect(found[0].timestamp).toBeNull()
})
})
```
=> api.specHelper.findEnqueuedTasks

__tests__/core/cli.js, bin/methods/generate.js, bin/methods/generate/action.js, bin/methods/generate/task.js, bin/templates/action.js, bin/templates/cli.js, bin/templates/initializer.js, bin/templates/server.js, bin/templates/test/action.js, bin/templates/test/task.js, config/api.js
Completes https://github.com/actionhero/actionhero/issues/1005
When generating a new `action` or `task` via the CLI, a template test will also now be creates in `__tests__`.  This will help encourage better testing of your actionhero projects.  Of course, you can always delete the test files if you don't want it.
Adds `api.config.general.paths.test` as setting in `./config/api.js` which defaults to `[path.join(__dirname, '/../__tests__')]`
=> create tests for actions and tasks when generating via CLI

config/api.js, index.js
Related to https://github.com/actionhero/ah-swagger-plugin/pull/6
If we change how Actionhero loads itself to *always* prefer components in `node_modules` relative to the `cwd` (current working directory):
**Pros**
* There is no change to the behavior or a normal actionhero project
* Globally installed Actionhero (`npm install -g actionhero`) is now resistant to minor version changes between projects
* Allows plugins to install a version of actionhero as a `devDependancy`, and for us to boot the project and not have conflicting paths to source actionhero from.  You can now just `npm start` (`./node_modules/.bin/actionhero`) in your plugins to start a server to run your plugins
**Cons**
* If you start actoinhero from a dameon (like `forever`) without first `cd`-ing to the proper directory …
=> Always prefer actionhero in node_modules

.github/FUNDING.yml
This PR adds a `FUNDING.yml` to actionhero.  [Learn more here](https://help.github.com/en/articles/displaying-a-sponsor-button-in-your-repository)
This will allow folks to sponsor to the maintainers/creators of Actionhero via Github Sponsorships. 
To start, this list only includes @evantahler.  We will need to come up with a policy for adding contributors to this list.
=> Allow funding support of actionhero

__tests__/core/middleware.ts, src/classes/actionProcessor.ts, src/classes/process.ts, tutorials/actions.md, tutorials/middleware.md
Now with Typescript, you'll get an error if you try to set arbitrary properties on the `data` object either within an action or middleware.  We need a place to pass data from the middleware to the action.
=> Allow for a session object in actionProcessor and Action data

templates/package.json.template
Right now ts-node-dev watches all direct dependencies in node_modules which is unnecessary. [Adding --no-deps](https://github.com/whitecolor/ts-node-dev/issues/51#issuecomment-512096067) makes server restarts *significantly faster*.  People shouldn't be modifying node_modules directly anyway and server restarts anyway when package.json changes, so I think this is a good thing to have by default.
=> Use --no-deps in ts-node-dev

src/bin/actionhero.ts, src/bin/methods/start.ts, src/bin/methods/start/cluster.ts
With so many other options to run node.js processes, like [PM2](https://pm2.keymetrics.io/) or your OS's background process manager (ie [`systemd`](https://tibbo.com/linux/nodejs/service-file.html)), we have removed the `--daemon` option from Actionhero
=> remove --daemon option to start actionhero

__tests__/core/specHelper.ts, src/modules/specHelper.ts
Adds a helper method `specHelper#deleteEnqueuedTasks` which can be used to remove all tasks in your test.
```ts
await task.enqueue("testTask", { a: 1 });
await task.enqueueAt(10, "testTask", { a: 1 });
// will delete tasks in both the normal and delayed queues
await specHelper.deleteEnqueuedTasks("testTask", { a: 1 });
const foundTasks = await specHelper.findEnqueuedTasks("testTask");
expect(foundTasks.length).toBe(0);
```
=> specHelper#deleteEnqueuedTasks

package-lock.json, package.json, src/initializers/resque.ts
When a task is complete, log how long it took in ms.
```
192.168.7.33 @ 2020-02-17T00:01:47.561Z - info: [ worker ] task success workerId=1 class=hello queue=default args={} duration=1007
```
=> log task durations

src/modules/cache.ts
Reimplementing https://github.com/actionhero/actionhero/pull/1265
--- 
From the original PR, via @cecofreeman
An item is loaded from the cache and is eventually old copy, because first is loaded and then is checked for locking. In such a case the locker worker may apply changes to the item during the lock, but we don't receive a fresh copy for the item. This fix is checking for lock first and then tries to load the item.
=> Check the lock when cache.get() 2x: before reading and before writing

src/classes/process.ts, src/server.ts, templates/projectServer.ts.template
* provide a callback to `app.registerProcessSignals` which will be called when the app is fully shut down.  This provides an explicit place to call `process.exit()`, which will in turn ensure that all sub-processes are exited too.
* on a `uncaughtRejection` or `uncaughtRejection`, try to gracefully shut down the server with `process.stop()`. 
* Wait `process.env.ACTIONHERO_SHUTDOWN_TIMEOUT` (or 30 seconds) and then `process.exit()`
* only catch one `uncaughtRejection` or `uncaughtRejection`
The recommended `server.ts` is now:
```ts
import { Process } from "./index";
// load any custom code, configure the env, as needed
async function main() {
// create a new actionhero process
const app = new Process();
// handle unix signals and uncaught exceptions & rejections …
```
=> Better Server Shutdown

.vscode/launch.json
We can use the integrated VSCode debugger to run Jest tests as well!  The normal breakpoints and debug console work as expected.
Downsides:
- If you are paused at a break point, that probably means your test will fail because it took too long (default 5 seconds)
- This VSCode task by default will run _every_ test in your project.  You will need to modify the `runtimeArgs` to pass in a single test file.
=> Add VSCode debug task for jest

__tests__/servers/web/routes/routes.ts, src/initializers/routes.ts
This PR allows `routes` to be matched against an arbitrary prefix before the ':' variable demarkation.  This allows things like `api/v2/myAction` when your action's version is `2`.  
```ts
// in routes.ts
export const DEFAULT = {
routes: (config) => {
return {
get: [{ path: "/v:apiVersion/myAction", action: "myAction" }],
};
},
};
```
Prior to this PR, the "v" before the ":" would always fail to match a request URL.
=> Implement ignorable route prefixes for static and regular-expression routes

.circleci/config.yml, __tests__/servers/web/routes/routes.ts, src/index.ts
This PR enforces the "globalness" of the `api` object within Actionhero projects.  It was previously possible to have 2 different instances of the `api` object with working with plugins that had 2 different Actionhero paths (ie, they were both importing Actionhero from their local node_modules).  This led to lots of problems with un-initialized initializers and missing parts of the api namespace.
Normally, using global objects is frowned upon... but we really do want to enforce a process-wide single instance.  
It is still recommenced to access the `api` object via `import {api} from 'actionhero'` and not use the global object.
---
There's no good way to pollyfil `globalThis` for some of the older node versions we support, so we are using `global`.
=> Global api object via `global`

__tests__/servers/web/allowedRequestHosts.ts, src/servers/web.ts
closes https://github.com/actionhero/actionhero/issues/1480
=> always rely on headers["x-forwarded-proto"]  if present to detect request protocal

src/classes/actionProcessor.ts, src/config/errors.ts, src/initializers/exceptions.ts
closes https://github.com/actionhero/actionhero/issues/1504
Actions and tasks now log to one line in the file and other transports.  The stack trace contains `\n` so it still is legible pretty in the console. 
**Action**
```bash
2020-06-25T00:48:24.045Z - error: [ action @ web ] to=127.0.0.1 action=broken params={"action":"broken","apiVersion":1} duration=1 error=TypeError: Cannot read property 'missing' of undefined stacktrace=TypeError: Cannot read property 'missing' of undefined
at ValidationTest.run (/Users/evan/workspace/actionhero/actionhero/src/actions/broken.ts:14:27)
at ActionProcessor.runAction (/Users/evan/workspace/actionhero/actionhero/src/classes/actionProcessor.ts:378:35)
at processTicksAndRejections (internal/process/task_queues.js:97:5) …
```
=> Action and Task errors log on only one line

__tests__/core/tasks/customQueueFunction.ts, src/config/tasks.ts, src/initializers/resque.ts
This PR allows `api.tasks.queues` to be either a static array or an async function that returns a list of queues.  This method will be called once when the server starts.  In this way, you can provide custom logic to build up your list of queues for this server.
```ts
// config/tasks.ts
export const DEFAULT = {
tasks: (config) => {
return {
_toExpand: false,
// Should this node run a scheduler to promote delayed tasks?
scheduler: false,
// what queues should the taskProcessors work?
queues: ["*"],
// Or, rather than providing a static list of `queues`, you can define a method that returns the list of queues.
queues: async () => { return ["queueA", "queueB"]; },
// ...
```
=> `config.tasks.queues` can be a static array or an async function that returns list of queues

__tests__/core/api.ts, src/classes/action.ts, src/initializers/actions.ts, src/initializers/params.ts
An expansion on https://github.com/actionhero/actionhero/pull/1520
This PR also moves calling `api.params.buildPostVariables()` to the action initializer so can load `api.params.globalSafeParams` earlier in the boot process.
---
Original Description:
issue:
My colleague meets the issue, he adds an "action" key in an action input...
but "action" is a keyword, apiVersion also.
can we have a checker to avoid it? even in build time or runtime.
[Example](https://github.com/allyusd/actionhero-action-inputs-using-reserved-params/blob/master/src/actions/usingReservedParams.ts)
problem:
I was tried to add `class/action.ts` validate using `api.params.globalSafeParams` of `initializers/params.ts`
But `action.validate` called by `initializers/action.ts` and its load priority is 410 and `params.ts` is …
=> Validate that Action inputs do not use reserved params

public/index.html, src/actions/swagger.ts
In environments other than `development`, we don't return `serverInformation` with API calls by default.   This PR changes the behavior of `index.html` to read the status values from the status action's response directly.
=> Do not rely on serverInformation for index stats

__tests__/core/tasks/tasks.ts, src/modules/task.ts
When calling `task.enqueueAllRecurrentTasks()` (which happens automatically at startup), there may be a race condition in which 2 instances of the recurring task are attempted to be enqueued at the same time.  Before this PR, one of the tasks would throw an error, and possibly end up in the resque error queue.   In reality, we only want one instance of each recurring task enqueued anyway, so we shouldn't throw... we now just log.
=> Do not throw error when enqueueAllRecurrentTasks encounters the task already enqueued

src/classes/actionProcessor.ts, src/initializers/exceptions.ts
Returns `api.exceptionHandlers.action` so that errors from actions can be passed to third-party error reporters.  IE:
```ts
api.exceptionHandlers.reporters.push((error: Error) => {
Sentry.captureException(error);
});
```
The `actionProcessor` still handles logging the action.
Related to https://github.com/actionhero/ah-sentry-plugin
=> Brings back api.exceptionHandlers.action for logging action errors with third-party error reporters

package-lock.json, package.json
As a reminder, Typescript doesn't follow Semver, so this isn't likely a breaking change.
=> Upgrade to Typescript v4

src/bin/actionhero.ts
It was previously 'start', which has been removed
=> Help should be the default command when running the Actionhero CLI

src/bin/methods/console.ts
When running `actionhero console` to get a CLI instance, we should not try to 'start' the server, only to initialize it.  Also, `config` is no longer mutable, so there's no reliable way to disable the servers if we did try to start the server.
=> Do not 'start' the server in the CLI console

src/classes/process.ts
Prevents a bug in which sending two stop signals to the Actionhero process (ie hitting `ctrl-c` rapidly) would short-circuit the work of the first stop signal.
=> Do not stop the shutdown timer on the second SIGINT/SIGTERM

__tests__/core/log.ts, src/classes/actionProcessor.ts, src/classes/process.ts, src/config/logger.ts, src/index.ts, src/modules/log.ts
You can now `import {loggers} from 'actionhero'` to access the winston loggers you created in `config/loggers`.
=> Export the winston loggers as "loggers" from Actionhero

__tests__/core/tasks/tasks.ts, package-lock.json, package.json, src/initializers/tasks.ts, src/modules/task.ts
While rare, it is possible to end up with more than one instance of a recurring task enqueued in your Actionhero Cluster at the same time.  The most common way to end up in this state is:
1. A recurring task fails and is placed in the error queue.
2. The server reboots (or another Actionhero server joins the cluster) and re-adds an instance of the task that failed.
3. The failed task instance is retried.
In these cases, You'll likely end up with an error on one of those tasks that looks like `Job already enqueued at this time with same arguments`.  This comes from Node Resque's Job Lock plugin which we are using to ensure that no more than one instance of a recurring task can be running at a time.  That, along with the `queueLock` and `delayedQueueLock` plugins eventually sort out that …
=> Do not try to re-enqueue a recurring task if another instance is already running

__tests__/actions/swagger.ts, __tests__/core/config.ts, __tests__/core/staticFile/compression.ts, __tests__/integration/browser.ts, __tests__/integration/sendBuffer.ts, __tests__/integration/sharedFingerprint.ts, __tests__/servers/web/allowedRequestHosts.ts, __tests__/servers/web/jsonp.ts, __tests__/servers/web/rawBody.ts, __tests__/servers/web/returnErrorCodes.ts, __tests__/servers/web/routes/deepRoutes.ts, __tests__/servers/web/routes/routes.ts, __tests__/servers/web/routes/veryDeepRoutes.ts, __tests__/servers/web/web.ts, src/actions/swagger.ts, src/config/routes.ts, src/config/servers/web.ts, src/initializers/routes.ts, src/servers/web.ts
Per the discussion in https://github.com/actionhero/actionhero/discussions/1579, Actionhero is removing the options `config.servers.web.simpleRouting` and `config.servers.web.queryRouting`.  These options were confusing, and generally conflicted with the `config/routes.ts` file.  We want to be clear to new users that the "right" way to define the routes for your Actionhero APIs is in `/config/routes.ts`.
That said, there are times when you may need to quickly build routes automatically from your actions, like when testing or deploying this core Actionhero project directly 😁.  For those cases, this PR adds a new option, `config.servers.web.automaticRoutes`.  This new option is similar-ish to the old `automaticRoutes` option, but differs in a few key ways:
* disabled by default.  New users …
=> Add automaticRoutes, Remove query and simple routing

__tests__/core/cache.ts, src/config/redis.ts, src/modules/cache.ts
Previous to this PR, `cache.keys()` and `cache.locks()` were using the `keys` redis command.  With large datasets, this can be slow and block other connections from doing work.  The better way is to use the scan command repeatedly with a cursor to not block the server for too long.  
This PR adds `cache.getKeys(pattern:string)` which uses `scan`.  `cache.keys()` and `cache.locks()` have been refactored to use `cache.getKeys`.  
The `cache.clean` method has been updated to accept an optional `pattern` for the keys to remove, as well as use a redis `pipeline` to speed things up.  Rather than make many requests per key, it will make one to delete all the keys it found.
There's a new config option required, `config.redis.scanCount` to provide how many keys we should scan for in each request. …
=> Use scan to read collections of redis keys and provide getKeys as a generic way to search for redis keys

__tests__/actions/swagger.ts, __tests__/core/api.ts, __tests__/integration/sendFile.ts, src/actions/cacheTest.ts, src/actions/createChatRoom.ts, src/actions/randomNumber.ts, src/actions/sendFile.ts, src/actions/sleepTest.ts, src/actions/status.ts, src/actions/swagger.ts, src/actions/validationTest.ts, src/classes/action.ts, src/classes/actionProcessor.ts, src/classes/connection.ts, src/classes/input.ts, src/index.ts, src/initializers/staticFile.ts, src/modules/tsUtils.ts, src/modules/tsUtils/assertEqualType.ts, src/modules/tsUtils/unwrapPromise.ts
The preferred way to describe an Action's run method is now by returning an object which you want to send to your consumers.  By doing this, you are building up a Typescript type which can then be used in your API to type-check API responses! 
For example:
```ts
// src/actions/randomNumber.ts
import { Action } from "actionhero";
export class RandomNumber extends Action {
constructor() {
super();
this.name = "randomNumber";
this.description = "I am an API method which will generate a random number";
this.outputExample = { randomNumber: 0.123 };
}
async run({ connection }) {
const randomNumber = Math.random();
const stringRandomNumber: string = connection.localize([
"Your random number is {{randomNumber}}",
{ randomNumber },
]);
return { randomNumber, stringRandomNumber };
}
}
```
Now, you …
=> Actions can return responses to determine response types

__tests__/core/cache.ts, src/modules/cache.ts
From https://github.com/actionhero/actionhero/pull/1611, we can now provide an optional argument `optionalScopePrefix` to `redis.keys()` to limit what keys we search for.
=> `cache.keys` can be provided an optionalScopePrefix

__tests__/core/config.ts, src/modules/config.ts
For most options in config, we load default values from the Actionhero package in case you are missing something.  However, we do not want to do this with routes.  This PR ignores all `config/route.ts` files which may exist within `node_modules`
=> Do not load routes from Actionhero core

__tests__/core/cli.ts, __tests__/core/staticFile/staticFile.ts, __tests__/integration/browser.ts, src/actions/status.ts, src/bin/actionhero.ts, src/bin/methods/generate/plugin.ts, src/bin/methods/help.ts, src/bin/methods/version.ts, src/classes/action.ts, src/classes/process.ts, src/classes/process/actionheroVersion.ts, src/classes/task.ts, src/config/api.ts, src/config/redis.ts, src/config/servers/web.ts, src/initializers/actions.ts, src/initializers/servers.ts, src/initializers/tasks.ts, src/modules/specHelper.ts, src/modules/task.ts, templates/boot.js.template
To Prepare Actionhero for the world of ESM Modules, this PR removes all instances of `require()` with `import` or `await import()`.  
The notable exception is the config system, which still relied on `require()`.  We need to wait for top-level await to be generally available in Node.js to upgrade the config system to use `import`.  This is because we need to be able to statically `import {config} from "actionhero"` and have all files and sub-configs loaded and resolved.  
See https://github.com/actionhero/actionhero/discussions/1571 for more context.
=> Replace `require` with `await import` where possible

src/initializers/redis.ts, src/initializers/tasks.ts
With `ioredis` "quit" will try to reconnect now.  We want to "end" the connections when shutting down.
=> Prefer the `end` command when disconnecting from redis

__tests__/actions/recursiveAction.ts, __tests__/actions/swagger.ts, __tests__/modules/action.ts, __tests__/tasks/runAction.ts, src/actions/recursiveAction.ts, src/classes/actionProcessor.ts, src/modules/action.ts, src/tasks/runAction.ts
This PR introduces `action.run()` which allows Actions to be run arbitrarily from elsewhere in the codebase.   With this, you can have one Action call another, have a Task run Action, etc.   Middleware for the the Action will be run.  `action.run()` creates a new proxy connection with only the arguments you provide to the method.
```ts
import { action } from "actionhero"
const nameOfAction = 'myAction'
const actionVersion = 'v1' // or leave null to use the latest version
const params = {key: 'value'} // the params which would be parsed from the client
const connectionProperties = {} // special properties on the connection which may be expected by the action or middleware.  Perhaps "session.id" or "authenticated = true" depending on your middleware
const response = await …
```
=> Actions can be called in-line

public/chat.html, src/actions/status.ts, src/modules/chatRoom.ts
This PR adds some improvements when redis is disabled, 
* Skip trying to load the `maxResqueQueueLength` key in the `status` action
* Wrap all uses of redis in the `chatRoom` module with a check to see if redis is enabled.  If not, provide a more meaningful error.  This is also what we do in the `cache` module.
=> Enable status action and show more useful errors when redis is disabled

src/actions/swagger.ts
In routes that contain lots of params, ie `/api/:username/:post/:comment`, swagger doesn't properly replace params after the first one.
=> Replace up to 5 params in routes for swagger

.github/workflows/test.yml, __tests__/integration/browser.ts, package-lock.json, package.json
In theory, Puppeteer is will be easier for folks to use.  It works cross-platform, knows how to install it's own version of Chrome and doesn't have an external dependency like `chrome-webdriver`.   
If only I can get it to run on CI...
=> Browser tests with Puppeteer rather than Selenium

__tests__/integration/ioredis-mock.ts, package-lock.json, package.json, src/actions/status.ts, src/config/redis.ts, src/initializers/chatRoom.ts, src/initializers/redis.ts, src/initializers/resque.ts, src/initializers/tasks.ts, src/modules/cache.ts, src/modules/chatRoom.ts, src/modules/specHelper.ts, templates/package.json.template
This PR allows Actionhero to be run with the [`ioredis-mock`](https://github.com/stipsan/ioredis-mock) package.  In this way, we can allow users of Actionhero to use **every** features of the framework, including cache, chat, and tasks, without a Redis server running locally.   This is a breaking change as it removes the `enabled` option on `config.redis`, as Redis is now always enabled, but possibly mocked.
Of course, no data will be persisted or shared between nodes unless you are using a "real" Redis server.  The default configuration of Actionhero (when a new project is generated with `npx actionhero generate`) is to assume that a real Redis server can be reached at `localhost`.  However, we make it easy to change by providing a `ioredis-mock`-based configuration commented out in …
=> Actionhero can be run with ioredis-mock (Redis is always enabled)

src/classes/process/typescript.ts
Replaces the old `process.env.ACTIONHERO_TEST_FILE_EXTENSION` with `process.env.ACTIONHERO_TYPESCRIPT_MODE` to more declaratively state if we should load typescript files or not.
=> Replace ACTIONHERO_TEST_FILE_EXTENSION with ACTIONHERO_TYPESCRIPT_MODE (boolean)

src/classes/process/typescript.ts
Fixes a bug introduced in #1668 - we want to still default to testing Typescript files
=> Test mode still continues to use Typescript

__tests__/actions/cacheTest.ts, __tests__/actions/randomNumber.ts, __tests__/actions/recursiveAction.ts, __tests__/actions/sleepTest.ts, __tests__/actions/status.ts, __tests__/actions/swagger.ts, __tests__/actions/validationTest.ts, __tests__/tasks/runAction.ts, src/actions/status.ts, src/modules/specHelper.ts
(Typescript) This PR updates the `specHelper` such that you can provide the Action or Task run method type to it so that the response type returned will defend by the Action.
```ts
import { Process, specHelper } from "actionhero";
import { RandomNumber } from "../../src/actions/randomNumber";
const RunMethod = RandomNumber.prototype.run;
const actionhero = new Process();
describe("Action", () => {
describe("randomNumber", () => {
beforeAll(async () => {
await actionhero.start();
});
afterAll(async () => {
await actionhero.stop();
});
test("generates random numbers", async () => {
// Now, the response type of `specHelper.runAction` will be known ahead of time!
const { randomNumber } = await specHelper.runAction<typeof RunMethod>(
"randomNumber"
);
expect(randomNumber).toBeGreaterThan(0); …
```
=> Type Action and Task responses in specHelper

package-lock.json, package.json
`@types/ioredis` is a required dependency.  It was improperly moved to a `devDependency` in https://github.com/actionhero/actionhero/pull/1672
=> @types/ioredis is a depenedency

src/bin/methods/generate/action.ts, src/bin/methods/generate/cli.ts, src/bin/methods/generate/initializer.ts, src/bin/methods/generate/server.ts, src/bin/methods/generate/task.ts, src/bin/methods/task/enqueue.ts
In combination with #1679, the Actionhero CLI commands now come with descriptions! 
```
➜  actionhero generate-task --help
Usage: actionhero generate-task [options]
Generate a new Task
Options:
--name <name>                The name of the Task to generate
--queue <queue>              The queue that this Task will run on
--description [description]  The description of this Task (default: "an actionhero task")
--frequency [frequency]      Should this Task run periodically? Frequency is in ms (default: "0")
-h, --help                   display help for command
Example:
actionhero generate task --name=<name> -queue=<queue> --description=[description] --frequency=[frequency]
```
=> Provide CLI option descriptions and show defaults

__tests__/core/plugins.ts, __tests__/testPlugin/dist/bin/hello.js, __tests__/testPlugin/src/bin/hello.ts, __tests__/testPlugin/tsconfig.json, src/bin/actionhero.ts, src/bin/methods/generate/initializer.ts, src/classes/cli.ts
Type the inputs of CLI commands.  Yo can now define CLI commands which accept both ARGS and OPTS.  Consider the following:
1. `actionhero hello evan` would be `hello <name>`, where is a **required argument**.
2. `actionhero hello --name evan` would be the `hello` command, with an option of `name`. 
Here's what both of those look like:
```ts
import {CLI} from 'actionhero'
export class HelloArguments extends CLI {
constructor() {
super();
this.name = "hello <name>";
this.description = "I say hello";
this.example = "actionhero hello evan"
}
}
async run({params}) {
console.log(`Hello, ${params._arguments[0]}`);
return true;
}
}
export class HelloOptions extends CLI {
constructor() {
super();
this.name = "hello";
this.description = "I say hello";
this.example = "actionhero hello --name evan" …
```
=> Type CLI input tpes and support both ARGS and OPTS

src/classes/process.ts
default behavior
```
npm run dev
> actionhero@25.0.10 dev
> ts-node-dev --transpile-only --no-deps ./src/server
[INFO] 17:58:04 ts-node-dev ver. 1.1.6 (using ts-node ver. 9.1.1, typescript ver. 4.2.4)
2021-04-22T00:58:05.746Z - emerg: Exception occurred in initializer `actions` during load
2021-04-22T00:58:05.747Z - emerg: Error with initializer step: "initialize"
2021-04-22T00:58:05.756Z - emerg: Error: Oh No!
at Object.index_1.api.actions.loadFile (/Users/evan/workspace/actionhero/actionhero/src/initializers/actions.ts:55:13)
at Actions.initialize (/Users/evan/workspace/actionhero/actionhero/src/initializers/actions.ts:102:27)
at Object.initializeFunction (/Users/evan/workspace/actionhero/actionhero/src/classes/process.ts:159:33)
at Object.asyncWaterfall …
```
=> use `ACTIONHERO_FATAL_ERROR_STACK_DISPLAY` to toggle showing the error stack or just message

src/bin/actionhero.ts, src/classes/cli.ts
When defining a CLI command, I wanted to be able to use a [Variadic option](https://github.com/tj/commander.js/#variadic-option), but did not find a way to do this through actionhero. Commander supports this by adding `...` to the placeholder so you'll get back an array of all the options the user specified when running the command.
This also adds the ability to customize the value placeholder to pluralize it in the help section or use a different word entirely.
Currently this is possible by adding the ellipsis to the key, but it has some consequences on the usage of the param later on.
=> [cli] add support for custom placeholder and variadic options

__tests__/core/process.ts, src/classes/process.ts
This PR allows `process.stop()` to be called with a "reason" or "reasons", eg `process.stop('something bad happened')`.  In this way, in the `stop()` methods of your initializers, you can inspect `process.stopReasons` to report errors, etc.
As part of this, if there's an error with an initializer,  the error thrown will end up as a `process.stopReasons`
=> Store the reason that `process.stop()` was called

src/config/redis.ts
This PR adds support for detecting a `rediss://`URL (Redis + TLS) and ignoring self-signed certificate warnings as a default configuration.
=> Support SSL redis connections

src/config/redis.ts
Closes https://github.com/actionhero/actionhero/issues/1786
This PR configures `config/redis` to create an SSL connection if:
1) `process.env.REDIS_SSL=true`
2) The `REDIS_URL` starts with `rediss://`. This is the pattern that Heroku has popularized. 
The extra `s` is for secure!
> As of Redis version 6, Hobby plans support both TLS and unencrypted connections, while production plans require TLS connections. For hobby plans you can find the unencrypted (plaintext) and TLS URIs in your app’s config vars REDIS_URL and REDIS_TLS_URL respectively. For Premium, Private, and Shield plans on version 6 your REDIS_URL config var will use the rediss: scheme, and you must enable TLS in your Redis client’s configuration in order to connect to a Redis 6 database. …
=> Support Redis over SSL with Environment Variable

__tests__/integration/browser.ts, __tests__/utils/utils.ts, package.json, src/config/api.ts, src/initializers/resque.ts, src/modules/utils/filterObjectForLogging.ts, src/modules/utils/filterResponseForLogging.ts
This PR allows `config.general.filteredParams` and `config.general.filteredResponse` to both be functions returning `string[]` in addition `string[]` directly.  In this way you can dynamically look up params you need to filter.
=> `config.general.filteredParams` and `config.general.filteredResponse` can be a function

src/classes/process.ts, src/initializers/servers.ts
Uses `${config.general.serverName}`, which in turn comes from `name` in `package.json` in the starting and stopping log messages:
```bash
2021-05-19T22:17:54.491Z - info: *** Starting Actionhero ***
2021-05-19T22:17:54.925Z - notice: *** Actionhero Started ***
2021-05-19T22:20:03.470Z - notice: *** Actionhero Stopped ***
2021-05-19T22:17:54.491Z - info: *** Starting MyApp ***
2021-05-19T22:17:54.925Z - notice: *** MyApp Started ***
2021-05-19T22:20:03.470Z - notice: *** MyApp Stopped ***
```
Also adds an `http://` in front of the web server start message to make it clickable in some terminals (eg: iterm, vscode).
=> Update Log messages

__tests__/utils/utils.ts, src/config/logger.ts, src/modules/utils/filterObjectForLogging.ts, src/modules/utils/filterResponseForLogging.ts
The new config param, `config.logging.maxLogArrayLength` can be used to limit the number of items logged for large arrays. The default value is 10.  This applies to logging the params/inputs of Actions and Tasks.
=> Limit the number of array elements to log

package-lock.json, package.json
In https://github.com/actionhero/actionhero/pull/1831, `@types/ioredis` was improperly moved to a devDependency.  This PR fixes it.
=> Return @types/ioredis as a dependency

src/classes/exceptionReporter.ts, src/classes/process.ts, src/index.ts, src/initializers/actions.ts, src/initializers/exceptions.ts
This PR refactors the Exception initializer and introduces some better types for a new `ExceptionReporter` type.  We then use `api.exceptionHandlers.report()` in the main process if something goes wrong rather than manually logging errors to the logger as we had been.
This PR's goal is to set up the `ExceptionReporter` for use elsewhere - eg perhaps you are using Sequelize which has [custom error types](https://sequelize.org/master/class/lib/errors/validation-error.js~ValidationError.html), and you want to make a new custom `ExceptionReporter` that gets these Sequelize errors and logs the SQL statement which caused the problem... hypothetically.
=> Better types for ExceptionReporter & use throughout

src/initializers/exceptions.ts
This PR extends https://github.com/actionhero/actionhero/pull/1853, updating the ExceptionReporter to always have a value for `data.stack`, even if the Error object doesn't have a stack trace.  In that case, we'll use `error.message` or `error.toString()`
=> If there is no `error.stack`, use the error message

src/classes/actionProcessor.ts, src/config/errors.ts, src/servers/web.ts
This PR improves a few things about Action logging:
1. [Enhancement] Action logs now include the `method` and `pathname` of the request, as seen by Actionhero, for web connections.
```
2021-06-30T00:05:53.156Z - info: [ action @ web ] to=127.0.0.1 action=createChatRoom params={"action":"createChatRoom","apiVersion":1,"name":"some room"} duration=1 method=GET pathname=/api/createChatRoom
2021-06-30T00:05:42.163Z - error: [ action @ web ] to=127.0.0.1 action=createChatRoom params={"action":"createChatRoom","apiVersion":1,"name":"foo"} duration=1 error=Error: room exists method=GET pathname=/api/createChatRoom stack=Error: room exists
at Object.add (/Users/evan/workspace/actionhero/actionhero/src/modules/chatRoom.ts:111:13)
at processTicksAndRejections …
```
=> Action Logging Improvements to aid `404` debugging

__tests__/core/tasks/tasks.ts, src/modules/task.ts
Hoist `api.resque.queue.delByFunction` to `task.delByFunction`
Closes https://github.com/actionhero/actionhero/issues/1784
=> Implement `task.delByFunction()`

src/initializers/tasks.ts
Closes https://github.com/actionhero/actionhero/issues/1817
```ts
import { Task } from "actionhero";
export default class RunAction extends Task { // <--- Now the "default" export works too
constructor() {
super();
this.name = "myTask";
this.description = "I am a test task";
this.frequency = 0;
this.queue = "default";
}
async run(params) {
console.log("Hello from task");
}
}
```
=> Support loading task as default file export

src/config/logger.ts
New Actionhero projects will come with an environment variable, `process.env.LOG_LEVEL` which can be used to set the log level for both the file and console logger.
=> Use `process.env.LOG_LEVEL` to set log level by default

src/classes/action.ts, src/classes/actionProcessor.ts, src/classes/exceptionReporter.ts, src/classes/server.ts, src/modules/log.ts
This may be a breaking change.
If the types include `string` then we no longer get the typescript autocomplete.
=> Added types for the loglevel

src/classes/action.ts, src/classes/actionProcessor.ts, src/classes/exceptionReporter.ts, src/classes/server.ts, src/index.ts, src/modules/log.ts
`ActionheroLogLevel` needs to be exported so consumers can type their logs
=> Rename `LogLevels` to `ActionheroLogLevel` and export

__tests__/core/chatRoom.ts, src/modules/chatRoom.ts
Fixes 2 related bugs about the storing and reading of chatRoom member details.  
Prior to this PR, we were not properly awaiting the (newly optionally) async methods `chatRoom.roomStatus` and `chatRoom.generateMemberDetails`, leading to empty hashes of data stored in redis for these connections.  This was visible most noticeably when calling `chatRoom.roomStatus()` and not seeing any information for the other members of the room.
Closes https://github.com/actionhero/actionhero/issues/1958
=> Fix the storage and retrival of chatRoom member details

src/servers/websocket.ts
Closes https://github.com/actionhero/actionhero/issues/1965
This PR use `fs.mkdirSync(path, { recursive: true });` to not throw if there was a race condition with 2 actionhero processes trying to create the client js lib's directory at the same time.  This was likely to happen in fast tests. 
```
$ node
Welcome to Node.js v16.6.1.
Type ".help" for more information.
> const fs = require('fs')
undefined
> fs.mkdirSync('/tmp/foo')
undefined
> fs.mkdirSync('/tmp/foo')
Uncaught Error: EEXIST: file already exists, mkdir '/tmp/foo'
at Object.mkdirSync (node:fs:1324:3) {
errno: -17,
syscall: 'mkdir',
code: 'EEXIST',
path: '/tmp/foo'
}
> fs.mkdirSync('/tmp/foo', {recursive: true})
undefined
```
=> Do not throw on race-condition when creating client JS directory

src/modules/specHelper.ts
I think it can be divided into two parts: generic type and return type from ```specHelper.runAction<A>()```
1. generic type from ```specHelper.runAction<A>()```
I choose to define the generic type as ```A extends Action | void = void```.  This allows to not provide type and if provide type, it must be ```Action```
- provide ```Action``` will be passed
- not provide type will be ```void``` and passed
- provide not ```Action```(provide ```Task```) will be rejected
2. return type from ```specHelper.runAction<A>()```
Providing ```Action``` will be the same as before. But if no type is provided(as provide ```void```), the "non-strict" type will be returned. The returned type should have some useful info(#2003 ), so I choose ```{[key: string]: any} & RequestExtraInfos```(For convenience, the …
=> specHelper runAction runTask runFullTask generic type variable can be optional

src/classes/actionProcessor.ts
This PR simplifies the arguments Actions pass to input Default, Formatters, and Validators.  Before this PR a second argument of `this` would be passed, which was the `api` object for some reason.  Now that accessing the `api` is object is as simple as `import {api} from 'actionhero'` this isn't needed.  This means that there are no un-expected inputs to your input methods.  
This PR also clarifies that the `this` scope of input methods is the Action Processor itself - so you'll have access to the action's class, the connection, etc - the same as `data` on the Action' s run method if you need it though `this.connection` and `this.actionTemplate`. 
This is technically a breaking change, although I don't think that was used...
=> Simplify the arguments to action formatters and validators

src/classes/process/id.ts
The changes made in https://github.com/actionhero/actionhero/pull/2014 around the cluster module need to be reverted.  The `@types` for this package are incorrect.  Crazy!
```ts
// not working
import cluster from "cluster";
console.log(cluster); // --> undefined
// working
import * as cluster from "cluster";
console.log(cluster); // --> 
EventEmitter {
_events: [Object: null prototype] {},
_eventsCount: 0,
_maxListeners: undefined,
isWorker: false,
isMaster: true,
isPrimary: true,
Worker: [Function: Worker],
workers: {},
settings: {},
SCHED_NONE: 1,
SCHED_RR: 2,
schedulingPolicy: 2,
setupPrimary: [Function (anonymous)],
setupMaster: [Function (anonymous)],
fork: [Function (anonymous)],
disconnect: [Function (anonymous)],
[Symbol(kCapture)]: false
}
```
=> Fix cluster import

__tests__/servers/web/routes/routes.ts, src/initializers/routes.ts
This PR fixes a bug with the Actionhero Router.
Prior to this PR, a route like `/v:apiVersion/status` would match `/1/status` when it shouldn't.  The expected matches should have a `"v"` in the routes, like `/v1/status`
=> Fixes router bug matching variable routes without a required prefix

__tests__/actions/swagger.ts, src/actions/swagger.ts
Allows replacement of more than 5 variables in the path by using the global flag in the regex. This works because technically `$1` is still the first capture group in the provided regex.
=> use global flag in swagger path substitution

package-lock.json, package.json, src/classes/process/typescript.ts
We need to know if Actionhero is running in Typescript (via `ts-node`, `ts-node-dev`, `jest`, or similar) to determine if we should load `/src/config/*.ts` or `/dist/config/*.js`
Prior to this PR, we assumed that any time that `NODE_ENV=test`, we should be running typescript and load the typescript config files.  This prevented anyone from using a CLI Actionhero command in CI.  This new way of guessing if we are running in typescript should be a bit safer.
=> Do not assume that all uses of Actionhero in test are running typescript

src/actions/cacheTest.ts, src/actions/createChatRoom.ts, src/actions/randomNumber.ts, src/actions/recursiveAction.ts, src/actions/sendFile.ts, src/actions/sleepTest.ts, src/actions/status.ts, src/actions/swagger.ts, src/actions/validationTest.ts, src/classes/inputs.ts, src/index.ts, src/tasks/runAction.ts
The new `ParamsFrom` TS utility can *finally* help dynamically determine the param types of an Action's run method!  This only works on Action classes that **statically** define the inputs, e.g. NOT in a constructor.  Here's a screenshot of things working:
Note that `params.value` is properly a string, and we get an error that `params.foo` is undefined.
Here's the magic:
```ts
export type ParamsFrom<A extends Action | Task> = {
[Input in keyof A["inputs"]]: A["inputs"][Input]["formatter"] extends (
...ags: any[]
) => any
? ReturnType<A["inputs"][Input]["formatter"]>
: string;
};
```
What's nice about this approach is that we don't need to change any of Actionhero's internals, but we should start writing all of our Actions and Tasks with static definitions.
=> `ParamsFrom` utility to determine types of params from Action Inputs

__tests__/modules/config.ts, src/classes/process.ts, src/classes/process/actionheroVersion.ts, src/classes/process/env.ts, src/classes/process/id.ts, src/classes/process/pid.ts, src/classes/process/projectRoot.ts, src/classes/process/typescript.ts, src/modules/config.ts
Adding rebuild config method. Calling rebuild config method on server restart.
=> Rebuild Config on Server Restart

__tests__/cli/cli.ts, __tests__/testCliCommands/hello.ts, package.json, src/bin/actionhero.ts, src/classes/inputs.ts
Moves to using commander's [built-in option processing](https://github.com/tj/commander.js#custom-option-processing) when running `formatter` and `validator` functions on CLI inputs.
This lets commander give us better output in the case of validation errors (as opposed to showing a full stack trace as currently happens).
```
▲ actionhero % actionhero something --test blah.
error: option '--test [test]' argument 'blah.' is invalid. blah. isnt valid because periods are bad
```
**Possibly breaking**: `formatter` and `validator` can no longer be asynchronous for CLI inputs.
=> use commander to handle cli `formatter`/`validator`

__tests__/cli/cli.ts, __tests__/testCliCommands/hello.ts, src/bin/actionhero.ts, src/classes/cli.ts
When using non-required CLI inputs, the use of the `[ ]` separators means it's allowed to pass in the option without a value, getting a boolean in return:
```js
program
.option('-c, --cheese [type]', 'Add cheese with optional type');
program.parse(process.argv);
const options = program.opts();
if (options.cheese === undefined) console.log('no cheese');
else if (options.cheese === true) console.log('add cheese');
else console.log(`add cheese type ${options.cheese}`);
```
```
$ pizza-options
no cheese
$ pizza-options --cheese
add cheese
$ pizza-options --cheese mozzarella
add cheese type mozzarella
```
(example from https://github.com/tj/commander.js#other-option-types-negatable-boolean-and-booleanvalue)
However, when passing an option we often dont want to allow the boolean case and want …
=> cli command optional inputs can require a value

__tests__/testCliCommands/hello.ts, src/classes/inputs.ts, src/index.ts
For some reason, TypeScript has trouble inferring types properly when using `A extends CLI` as a conditional.
You can play around with this example here https://github.com/actionhero/actionhero/commit/eee6e8dcab5bcfe795fe70c262f1d9f7b6909ab3
Separating out ParamsFrom for the CLI to it's own type lets you explicitly use it, though I'd still like to find a solution that keeps things in a single `ParamsFrom` that works for both if possible, hence the draft PR. Pushed here for visibility.
=> fix `ParamsFrom` type inference

__tests__/utils/utils.ts, src/bin/actionhero.ts, src/classes/process.ts, src/initializers/actions.ts, src/initializers/servers.ts, src/initializers/tasks.ts, src/modules/config.ts, src/modules/utils.ts, src/modules/utils/safeGlob.ts
Closes https://github.com/actionhero/actionhero/issues/2275
=> Fix glob problems with path's in windows, safeGlobSync implemented.

templates/package.json.template
After https://github.com/actionhero/actionhero/pull/2278, generated projects now need `@types/glob`
=> `@types/glob` is now required for generated projects

__tests__/servers/websocket.ts, src/config/web.ts
In node.js v18, when binding to `0.0.0.0`, it will attach to either an ipv4 or ipv6 stack, depending on what the default is for your computer.  This can be confusing because binding the server to `0.0.0.0` on MacOS for instance, will repond to ipv6 requests (`http://::1:8080`) but not ipv4 (`http://localhost:8080`).
This PR changes the default behavior of the web server to bind to `::`, which should work for both ipv4 and ipv6.
=> Webserver binds to `::` by default

__tests__/core/cluster.ts, src/initializers/chatRoom.ts
`removeMember` can be called as an RPC method [here](https://github.com/actionhero/actionhero/blob/main/src/modules/chatRoom.ts#L273). Since `removeMember` is not on the `api.chatRoom` object, it does not get executed and just logs `RPC method chatRoom.removeMember not found`.
=> add removeMember to api.chatRoom

src/actions/swagger.ts, src/config/web.ts, src/servers/web.ts
As described [here](https://github.com/node-formidable/formidable#formidable--incomingform) options for IncomingForm should be passed to the contructor directly.
=> Pass options to form contructor

__tests__/actions/validationTest.ts, src/actions/validationTest.ts, src/classes/actionProcessor.ts
Currently, there is no way to use generic validators that include the name of the invalid parameter in the error message.
Expected functionality:
```ts
function validateXYZ(param: string, name: string) {
if (...) {
throw new Error(`Parameter ${name} is of type ${...} (expected ${...})`)
}
} 
```
This PR allows for this by passing `key` as extra parameter. Also, it's backwards compatible as additional arguments are ignored.
=> Allow validators to have access to their param name

__tests__/servers/web/enableMultiples.ts, __tests__/servers/web/nonMultiples.ts, src/config/web.ts
re: https://github.com/actionhero/actionhero/issues/2834
We already have some tests for this case in https://github.com/actionhero/actionhero/blob/main/__tests__/servers/web/enableMultiples.ts
UPDATE: Enabling this by default would be a breaking change, as most arguments in POST/PUT would become arrays.  So, instead, we'll show that the option exists and explain what it does.
=> Show `multiples` form options as optional argument to help users
