actionhero/actionhero

bin/templates/server.js, grunt/tasks/console.js, initializers/genericServer.js, initializers/servers.js, initializers/specHelper.js, servers/socket.js, servers/web.js, servers/websocket.js
- rename _start() to start() and _stop() to stop()
-  all server setup methods now called "initialize"
=> Server config update

README.md
Quick update to the readme to provide more constant formatting and improved rendering for higher-dpi screens
=> SVG image update

actionhero.js
this is in regards to discussion over here https://groups.google.com/forum/#!topic/actionhero-js/rEFGn1xVjdI..
=> recursively loading initializers

initializers/routes.js, test/servers/web.js
Regular expression match of routing, was not able to use the grouping.
=> fix route regexp

package.json
nodejitsu is shutting down... lets move somewhere else... to heroku! 
https://blog.nodejitsu.com/nodejitsu-joins-godaddy/
=> move demo.actionherojs.com to heroku

actionhero.js
if your current folder contains any "." in it ... all initalizers will break. this PR uses a nodejs path function to solve this.
=> resolve issue with additional "." in initalizer path

config/errors.js, initializers/actionProcessor.js
We need to handle invalid params and return custom structures, not only strings.
=> Add invalidParams message handler

docs/servers/web.md
Added some more detail to the Params section of the web server docs
=> Some spelling and wording fixes, as well as updating `action.inputs`

docs/core/initializers.md
Update the docs for initializers for v10.
=> Initializer doc updates

docs/servers/web.md
Updated documentation for routes for Actionhero v10.
=> Update routefile documentation for v10

_includes/footer.html, docs/core/stats.md
Also "Fork me" red ribbon, top right corner.
Looks good imho. Easier to get to repos :)
=> typo witeFrequency fix.

_includes/footer.html
Hide on small & x-small screens.
good call on hiding it for mobile~
=> Fork me button added.

config/servers/websocket.js, servers/websocket.js
Just a simple correction of documentation here.
It would also be totally reasonable to change this back to `null` and correct where the config is used in `servers/websocket.js:166`.
=> This actually needs to be `undefined`

actions/cacheTest.js, actions/randomNumber.js, actions/showDocumentation.js, actions/sleepTest.js, actions/status.js, bin/templates/action.js, initializers/actionProcessor.js, initializers/connections.js, initializers/exceptions.js, initializers/genericServer.js, initializers/specHelper.js, servers/socket.js, servers/web.js, servers/websocket.js, tasks/runAction.js, test/core/api.js, test/core/binary.js, test/core/exceptions.js, test/core/middleware.js, test/servers/socket.js, test/servers/web.js, test/servers/websocket.js
Reverts evantahler/actionhero#621
=> Revert "[HOLD] V11.0.0"

bin/templates/action.js, config/api.js, config/logger.js, initializers/actionProcessor.js, initializers/actions.js, initializers/chatRoom.js, initializers/connections.js, test/core/actionCluster.js, test/core/middleware.js, test/servers/socket.js, test/servers/websocket.js
New Middleware Syntax:
Action middleware syntax is now:
```javascript
api.actions.addMiddleware(definition);
// I.E.
api.actions.addMiddleware({
name: 'userId checker',
global: false,
priority: 1000,
preProcessor: function(data, next){
if(!data.params.userId){
next(new Error('All actions require a userId') );
}else{
next(err);
}
}
postProcessor: function(data, next){
if(data.thing.stuff == false){
data.toRender = false;
}
next(err);
}
});
```
- action middleware can now define both a preProcessor and postProcessor as a tuple.
- action middleware by default is applied to no actions, unless you define `definition.global = true`
- actions now opt into actions with the `action.middleware` array where names of actions are supplied which are to be invoked by each action, ie:
```javascript …
```
=> new middleware syntax

docs/core/chat.md, docs/core/middleware.md
=> Replaced api.connections.addMiddleware with api.chatRoom.addMiddleware

docs/docs/core/middleware.md, docs/docs/core/plugins.md
Minor spelling change and update to include swagger plugin
=> ah-swagger-plugin

config/tasks.js
=> Fix a typo

config/servers/web.js, servers/web.js
Even though it will slow down your web server, allow folks to optionally enable GZIP compression for actionhero/servers/web.
=> compression for web server

initializers/genericServer.js, initializers/staticFile.js, servers/web.js, test/core/staticFile.js
This pull request aims to improve the cache capabilities of the web server using "if-modified-since" specification.
=> support if-modified-since specifications

client/actionheroClient.js
=> Fixed issue with websockets remaining open

actionhero.js, config/logger.js, initializers/specHelper.js, initializers/utils.js, site/source/includes/docs/core/api_object.md, site/source/includes/docs/core/logging.md, site/source/includes/docs/utils.md, test/servers/socket.js, test/utils/utils.js, test/zzz_benchmarks/benchmarks.js
Remove no-longer used utils:
- api.utils.sqlDateTime(time)
- api.utils.sqlDate(time)
- api.utils.randomString(chars)
-  api.utils.sleepSync(seconds)
- api.utils.randomArraySort(arr)
- api.utils.inArray(haystack, needle)
=> Remove old utils

actionhero.js
I'll try to keep an eye on these little fellas :)
=> Deleted a trailing comma and some blank space.

config/redis.js, initializers/redis.js, package.json, site/source/includes/docs/core/api_object.md
solves: https://github.com/evantahler/actionhero/issues/740
solves: https://github.com/evantahler/actionhero/pull/692
related to https://github.com/taskrabbit/node-resque/pull/113
=> keyword 'package' to 'pkg' change

initializers/actionProcessor.js, site/source/includes/docs/core/actions.md, test/core/api.js
Since `formatter`, `validator`, and `default` are sync methods, we can change their `this` to be API.  That will be handy.
=> input methods have `api` set as `this`

site/source/includes/docs/core/actions.md
=> Change connection to data.connection in docs

site/source/includes/docs/core/plugins.md
Added the usual NPM -- in the plugin link command. Also corrected a couple of typos :-)
=> correct npm run command

site/source/includes/docs/core/plugins.md
Trying again, the NPM command needs to be npm run actionhero link -- --name nameOfPlugin rather than npm run actionhero link --name nameOfPlugin
=> correct npm run command - 2nd try

config/servers/web.js
=> Super duper minor typo

actionhero.js, bin/methods/startCluster.js, config/i18n.js
Will detect if all the workers under the cluster are crashing rappidly (2x # workers in 30s by default), and stop the process if this is detected
=> flapping detection in startCluster

actionhero.js, initializers/redis.js
For some redis clients (ioredis), subscriptions need to be set before joining sentinels.  This change should allow this without error.   
Related ioredis issue: https://github.com/luin/ioredis/issues/255
=> Update Redis Subscribe Order

initializers/redis.js
=> wrapping a 'package', get it?

config/api.js
Node likes to do things for us!
=> Temp dir issues on Windows

initializers/config.js
Only enable the callbacks to `api.watchFileAndAct` when `api.running === true`.  This helps us in 2 ways:
- prevents badly formatted or error'd initializers from constantly getting reloaded until we get at least one clean boot of the server. 
- solves #780, which was caused by both the actionhero server and the actionhero binary (which wraps the actionhero server) *both* watching the file... and trying to react to the change.
=> only reload server (in development mode) when running

includes/docs/core/chat
=> Small typo.

bin/methods/startCluster.js
silly javascript... defaulting to string comparisons...
=> fix cluster workers IDs > 10

test/template.js.example
Simply correcting the async test example for the status action
=> Async test for the status action was always passing since the done param was missing

initializers/servers.js
Thanks for your help Mr. Evan. Here's an update to log on startup what IP and port the servers bind to.
--Paul
=> logging what ip and port are bound to

bin/templates/action.js
1. Newline at beginning of file. Stylistic more than anything.
2. Space before curly brace on functions.
3. let instead of var
Thoughts?
=> Templating Change

bin/methods/startCluster.js, site/README.md, site/source/includes/docs/core/actions.md, site/source/includes/docs/core/initializers.md, site/source/includes/docs/getting_started.md, site/source/includes/docs/ops/production_notes.md
I fixed a few typos, and some small language changes to match the current docs site (project structure map is to the right, for instance)
=> Small typos and language fixes

site/source/includes/docs/servers/websocket.md
=> Typo fixes

site/source/includes/docs/servers/web.md
docsdocs is a pretty great url tho
=> more typos

site/source/includes/docs/core/cache.md
new is a reserved keyword, modifying to prevent errors in copy+paste. ¯\\_(ツ)_/¯
=> Example Code Fix

site/source/includes/docs/core/action_cluster.md
=> Typo & minor additional documentation

initializers/servers.js, initializers/tasks.js, test/core/tasks.js, test/zzz_benchmarks/benchmarks.js
solves https://github.com/evantahler/actionhero/issues/832
=> remove started counters and use async

package.json
=> Bumped node-resque version to ^2.0.5

initializers/utils.js
solves https://github.com/evantahler/actionhero/issues/847
=> fix crash due to missing logger in linked config setup

servers/web.js
related to: https://github.com/nodejs/node/issues/6929
=> handle prematurely closed file pipes in web server

bin/actionhero, bin/methods/unlink.js, bin/templates/help.txt, site/source/includes/docs/core/plugins.md
fixes https://github.com/evantahler/actionhero/issues/849
=> ActionHero unlink method

site/source/includes/docs/core/actions.md
=> Typoooosssss

initializers/tasks.js, test/core/tasks.js
fixes https://github.com/evantahler/actionhero/issues/863
=> fixup api.task.details; add a test

config/redis.js, initializers/cache.js, initializers/chatRoom.js, initializers/redis.js, initializers/resque.js, site/source/includes/docs/core/cache.md, site/source/includes/docs/core/chat.md, site/source/includes/docs/core/tasks.md, site/source/includes/docs/ops/production_notes.md, test/core/cache.js
```js
var host     = process.env.REDIS_HOST || '127.0.0.1';
var port     = process.env.REDIS_PORT || 6379;
var db       = process.env.REDIS_DB   || 0;
var password = process.env.REDIS_PASS || null;
exports['default'] = {
redis: function(api){
// konstructor: The redis client constructor method
// args: The arguments to pass to the constructor
// buildNew: is it `new konstructor()` or just `konstructor()`?
if(process.env.FAKEREDIS === 'false' || process.env.REDIS_HOST !== undefined){
return {
'_toExpand': false,
client: {
konstructor: require('ioredis'),
args: [{ port: port, host: host, password: password, db: db }],
buildNew: true
},
subscriber: {
konstructor: require('ioredis'),
args: [{ port: port, host: host, password: password, db: db }],
buildNew: true
},
tasks: {
konstructor: …
```
=> even better redis conf

servers/web.js, test/core/staticFile.js
solves https://github.com/evantahler/actionhero/issues/879
=> UTC date headers

.eslintrc, actions/status.js, initializers/utils.js, test/zzz_benchmarks/benchmarks.js
Add more data
- include event loop delay
- include memory consumption (HEAP)
- total resque queue length
Return a "healthy" or "unhealthy"  response based on this new data (and configurable via ENV)
=> Better status action

site/source/includes/docs/ops/upgrade_path.md
I think It explains the basics.
=> Added intro to upgrade_path.md

initializers/tasks.js, site/source/includes/docs/core/middleware.md, test/tasks/middleware.js
Addresses https://github.com/evantahler/actionhero/issues/899
@evantahler: I think it really is this easy.
=> Adds hooks for before_enqueue and after_enqueue to task middleware.

bin/methods/start/cluster.js, site/source/includes/docs/core/action_cluster.md, site/source/includes/docs/ops/production_notes.md, site/source/includes/docs/ops/running_actionhero.md, site/source/includes/docs/ops/testing.md, site/source/includes/docs/ops/upgrade_path.md
=> docs clarifications

bin/methods/start/cluster.js
=> fix typo - cluster.js

bin/methods/start/cluster.js, bin/templates/help.txt, site/source/includes/docs/ops/running_actionhero.md
run cluster mode, it would be useful to show who joined cluster.
=> add workerTitlePrefix option

servers/web.js, test/core/staticFile.js
I have stumbled into this pull request while debugging a problem with IE and activated actionhero compression.
IE will fail to display contents when compression and http secure is activated at the same time. I searched a bit and found some sources that involved headers bytes of the DEFLATE encoding being set or not resulting in IE being able to decode the stream (or fail to).
In succession, i tried switching the order of the deflate/gzip accept-encoding check to see how well IE is able to handle GZIP instead of the previously favored DEFLATE. ...And it did handle it well. I read that IE will never send the DEFLATE argument as first item in the list of supported encodings. Therefore I implemented a check about the order of the accepted encodings when applying a compression.
This won't fix …
=> Respect accept-encoding priority order as set by request header

docs/_includes/docs/core/action_cluster.html, docs/_includes/docs/core/actions.html, docs/_includes/docs/core/api_object.html, docs/_includes/docs/core/cache.html, docs/_includes/docs/core/chat.html, docs/_includes/docs/core/config.html, docs/_includes/docs/core/middleware.html, docs/_includes/docs/core/plugins.html, docs/_includes/docs/core/tasks.html, docs/_includes/docs/core/utils.html, docs/_includes/docs/deployment/development_mode.html, docs/_includes/docs/deployment/production_notes.html, docs/_includes/docs/deployment/testing.html, docs/_includes/docs/examples/examples.html, docs/_includes/docs/servers/web.html, docs/_includes/learn-more/companies.html, docs/_includes/learn-more/features.html, docs/_includes/learn-more/overview.html, docs/assets/css/style.css, public/css/actionhero.css
I love ActionHero!  I'm glad to be able to give back to the community.
=> Corrected typos in docs section.

README.md, docs/_includes/docs/core/actions.html, docs/_includes/learn-more/overview.html
This isn't all of them, but here is what I've found so far.
=> Fixed broken links in docs

config/servers/web.js, servers/web.js, test/servers/web.js
solves https://github.com/actionhero/actionhero/issues/1081
=> store connection.rawConnection.params.rawBody on web connections to keep around raw POST body

actions/cacheTest.js, actions/createChatRoom.js, actions/randomNumber.js, actions/showDocumentation.js, actions/sleepTest.js, actions/status.js, bin/methods/generate.js, bin/templates/action.js, classes/action.js, index.js, initializers/actions.js, package-lock.json, package.json, test/actions/cacheTest.js, test/actions/sleepTest.js, test/core/binary.js, test/core/cache.js, test/core/developerMode.js, test/servers/web.js
```js
'use strict'
const ActionHero = require('actionhero')
module.exports = class RandomNumber extends ActionHero.Action {
super()
this.name = 'randomNumber'
this.description = 'I am an API method which will generate a random number'
this.outputExample = { randomNumber: 0.123 }
}
async run (api, data) {
data.response.randomNumber = Math.random()
data.response.stringRandomNumber = data.connection.localize(['Your random number is {{number}}', {number: Math.random()}])
}
}
```
A more elaborate example with validators and inputs can be found here https://github.com/actionhero/actionhero/blob/434e9a10b0776c9b90dac1a639d7174eb9452070/actions/cacheTest.js
* defaults set by inheritance 
* properties (like name, description, etc) can me methods or strings
* extendible actions …
=> Action classes

actions/cacheTest.js, actions/createChatRoom.js, actions/randomNumber.js, actions/showDocumentation.js, actions/sleepTest.js, tasks/runAction.js
This PR is a part of the [PR 1088](https://github.com/actionhero/actionhero/pull/1088) work being done.
=> [Promise] Destructuring function parameters

bin/methods/start.js, bin/templates/task.js, classes/process.js, classes/task.js, index.js, initializers/resque.js, initializers/servers.js, initializers/tasks.js, tasks/runAction.js, test/core/api.js, test/core/cli.js, test/core/tasks.js
```js
'use strict'
const ActionHero = require('./../index.js')
module.exports = class MyTask extends ActionHero.Task {
super()
this.name = 'say-hi'
this.description = 'an actionhero task'
this.frequency = 5000
this.queue = 'default'
this.middleware = []
}
async run (api, data) {
console.log('*** HI! ***')
}
}
```
=> Classy tasks

actions/sleepTest.js, bin/methods/console.js, bin/methods/start.js, bin/methods/start/lib/actionheroCluster.js, classes/process.js, docs/api.cache.html, docs/api.staticFile.html, docs/initializers_cache.js.html, docs/initializers_staticFile.js.html, initializers/cache.js, initializers/chatRoom.js, initializers/staticFile.js, test/core/cache.js, test/core/chatRoom.js, test/core/cli.js, test/core/cluster.js, test/core/developerMode.js, test/core/i18n.js, test/core/tasks.js, test/integration/sharedFingerprint.js, test/servers/socket.js, test/servers/web.js, test/servers/websocket.js, test/utils/utils.js
Hooray for new built-in node helper methods!
=> use util.promisify where we can

initializers/chatRoom.js, initializers/specHelper.js, initializers/tasks.js, initializers/utils.js
Found some typos and missing documentation.
=> Fixing typos while backporting docs.

initializers/actions.js, initializers/chatRoom.js, initializers/config.js, initializers/connections.js, initializers/documentation.js, initializers/exceptions.js, initializers/i18n.js, initializers/id.js, initializers/params.js, initializers/pids.js, initializers/redis.js, initializers/resque.js, initializers/routes.js, initializers/servers.js, initializers/specHelper.js, initializers/staticFile.js, initializers/tasks.js, initializers/utils.js
=> Adding missing namespace headers to initializers.

circle.yml, servers/web.js
Ensure that ActionHero works on node.js v9.
* Use logic to handle changes in `parsedURL` from https://github.com/actionhero/actionhero/pull/1152
* Ensure we test both node v8 and v9 on Circle.ci
=> test node v9 and update parsedURL.search

bin/actionhero, classes/process.js
@bhagaban request handling syntax error in initializer
=> increasing verbosity for fatal error on handleMethod

initializers/utils.js, servers/web.js, servers/websocket.js, test/utils/utils.js
Added parseHeaderForClientAddress method to get the correct ip address
=> added: api.utils.parseHeaderForClientAddress(headers)

initializers/routes.js, test/servers/web.js
api.routes.registerRoute method could check for “all”
=> api.routes.registerRoute for "all" methods

package-lock.json, test/servers/web.js
testing stuff related to https://github.com/actionhero/actionhero/pull/1184
=> add some more tests explorign bad mime types

__tests__/servers/socket.js, bin/methods/start/lib/actionheroCluster.js, classes/process.js, initializers/chatRoom.js
Changes to allow `await` to occur in intended/existing `async` functions (not anonymous functions inside `.forEach`)
=> forEach() handling of async changed to for..of

initializers/tasks.js, tutorials/middleware.md
Figured it out from reading https://github.com/actionhero/actionhero/issues/1175
Resubmit of #1232
=> Fix task-oriented middleware documentation.

initializers/redis.js
I tried your fix but my tests suite fails due to the same issue. I propose moving the publish call in the return promise. That seems to fix it.
=> Another fix for do cluster #1246

__tests__/servers/socket.js
This should help the tests for the socket server be less brittle maybe
=> no sleep in socket tests; all promises and callbacks

tutorials/tasks.md
this fixes the Github issue I raised in #1289
=> fixed initializers/node_schedule.js example

config/api.js, initializers/actions.js, initializers/tasks.js, tutorials/development-mode.md
Resolves #1275
Opted to make this configurable with the default being the old behavior.
I tested the new code paths, but didn't create new test cases (primarily due to my doubts that this can be automatically tested at all).
=> Implemented config option to force "full" reload on action/task change

bin/actionhero
When running `actionhero generate plugin` in an empty directory, we cannot try to load local config
=> Fix Generate plugin

README.md, package-lock.json, package.json, tutorials/advanced.md, tutorials/config-and-dev.md, tutorials/core.md, tutorials/tutorials.json, typedoc.json
=> Tutorial TypeDocs

README.md
=> Update links in Readme to TS-Docs

package-lock.json, package.json, src/servers/web.ts
This package is now written in Typescript
=> Update Browser Fingerprint

package-lock.json, package.json, src/initializers/resque.ts
Before
```
info: [ worker ] job success workerId=1 class=hello queue=default
```
After
```
info: [ worker ] job success workerId=1 class=hello queue=default args={"thing":"[FILTERED]", "id": 123}
```
We use `config.general.filteredParams`, like the web server, to decide what params to filter when logged.
=> Filter and include task arguments in resque log messages

package-lock.json, package.json, src/classes/actionProcessor.ts
If an Action or Action Middleware throws an exception, we now log the full stack trace:
=> Action errors

__tests__/core/tasks/tasks.ts, src/classes/input.ts, src/classes/task.ts, src/modules/task.ts
Like Actions, Tasks can now define the inputs they expect.   This is optional.
Inputs can be:
* required
* default
* validated
Unlike actions, we don’t need a formatter, as the inputs should already be of the proper type, coming from the server.  We can check the inputs at ‘enqueue’ rather than at runtime. This will ensure that no task without the required inputs is enqueued.
For example, with this task: 
```ts
import { Task } from "actionhero";
class SendWelcomeEmail extends Task {
constructor() {
super();
this.name = "sendWelcomeEmail";
this.description = "send a new user a welcome email";
this.queue = "email";
this.frequency = 0;
this.inputs = {
email: { required: true },
template: { required: true, default: "welcome-email-en" }
};
}
async run(params) {
// send the email
}
}
```
* …
=> Tasks have inputs which are validated when enqueued

package-lock.json, package.json, src/initializers/redis.ts, templates/package.json.template
This will remove the dependency on projects using actionhero to install `@types/ioredis`
=> Remove ioredis type refrence

src/classes/server.ts, src/initializers/servers.ts
fixes for loading plugins that export a single server (as default) from a javascript file
=> Server plugin updates

templates/test/task.ts.template
=> Evan + Santiago: Fixed the generator for task tests

package.json, templates/package.json.template, tsconfig.json
Thanks to @gcoonrod and @allyusd and the 3/18 Actionhero Office hours!
This combined with the following vscode config enable awesome debugging! 
```json
// from .vscode/launch.json
{
"version": "0.2.0",
"configurations": [
{
"type": "node",
"request": "attach",
"name": "Actionhero Debugger",
"protocol": "inspector",
"port": 9229,
"restart": true,
"localRoot": "${workspaceFolder}",
"remoteRoot": "."
}
]
}
```
=> Add debugging examples and dev scripts

.gitignore, .vscode/launch.json, package.json, templates/package.json.template
Thanks to @allyusd and @gcoonrod!
From the Actionhero Office Hours on 4/22/20
Related to updates to the documentation website (see https://github.com/actionhero/www.actionherojs.com/pull/95)
=> better debugging support

public/index.html
This requires a modern-ish browser that actually has `fetch`... but that's the majority of browsers now.  closes https://github.com/actionhero/actionhero/issues/1472
=> replace ActionheroWebsocketClient with fetch in example index.html

__tests__/core/api.ts, __tests__/core/cache.ts, __tests__/core/chatRoom.ts, __tests__/core/cluster.ts, __tests__/core/errors.ts, __tests__/core/i18n.ts, __tests__/core/middleware.ts, __tests__/core/plugins.ts, __tests__/core/specHelper.ts, __tests__/core/tasks/fullWorkerFlow.ts, __tests__/core/tasks/tasks.ts, __tests__/integration/browser.ts, __tests__/integration/sendBuffer.ts, __tests__/integration/sharedFingerprint.ts, __tests__/servers/web/rawBody.ts, __tests__/servers/web/returnErrorCodes.ts, __tests__/servers/web/routes/routes.ts, __tests__/servers/web/web.ts, __tests__/servers/websocket.ts, src/classes/actionProcessor.ts, src/classes/connection.ts, src/classes/input.ts, src/classes/process.ts, src/index.ts, src/initializers/connections.ts, src/modules/task.ts
The exported `api` object from Actionhero has types!
=> Type the `api` object

.github/CONTRIBUTING.md, CODE_OF_CONDUCT.md, README.md
If you are in the USA, this week has been a difficult one.  This has been a week of turmoil and protests catalyzed by (yet another) unjust killing of a citizen at the hands of of the people who should be protecting all of us.  I try hard to not entangle this community with larger societal issues - to keep us focused only on code and APIs... but sometimes the real world intervenes. 
When thinking about what small things I can do to help ensure that the communities I'm a part of are open to _all_ people, I realized that I've been negligent in drafting a Code of Conduct for our community.   This PR adds a Code of Conduct that will govern those of us who work on Actionhero going forward, and to codify my goal of making our community as available as possible to the most people. 
I feel that it …
=> Add a Code of Conduct for the Actionhero Community

src/server.ts, templates/projectServer.ts.template
related to https://github.com/actionhero/actionhero/issues/1421 and https://github.com/actionhero/example-with-custom-env
=> Await the import of Actionhero so it is simpler to modify env

__tests__/integration/taskFlow.ts, src/initializers/tasks.ts
Closes https://github.com/actionhero/actionhero/issues/1515
=> Fix task start order and integration test

Dockerfile, docker-compose.yml
This will replace #1580 and removes the huge number of merge commits.
=> Update Dockerfile base image to node:alpine

src/bin/methods/task/enqueue.ts, src/initializers/resque.ts, src/initializers/tasks.ts
Closes https://github.com/actionhero/actionhero/issues/1584
=> Connect to Resque Queue at in initialize lifecycle step

package-lock.json, package.json
Details in https://github.com/actionhero/node-resque/pull/453
=> node-resque v8

README.md
> Technology is a powerful force in our society. Data, software, and communication can be used for bad: to entrench unfair power structures, to undermine human rights, and to protect vested interests. But they can also be used for good: to make underrepresented people’s voices heard, to create opportunities for everyone, and to avert disasters. This project is dedicated to everyone working toward the good.
>
> > Inspired by Martin Kleppmann
=> Add a Dedication to the Readme

src/modules/chatRoom.ts
Try to improve the explanation of parameters, but finally, I'm note sure that it's better, 
feel free to participate on this PR
=> doc: chatRoom broadcast, improve doc header 

.github/workflows/test.yml, __tests__/integration/browser.ts
install puppeteer dependencies
launch puppeteer with no-sandbox
ref: puppeteer/puppeteer#3443 (comment)
=> fixed ci fail for puppeteer

package-lock.json, package.json
https://github.com/actionhero/node-resque/releases/tag/v8.2.0
=> Upgrade to Node Resque v8.2.0

src/bin/actionhero.ts, src/bin/methods/generate/action.ts, src/bin/methods/generate/cli.ts, src/bin/methods/generate/initializer.ts, src/bin/methods/generate/server.ts, src/bin/methods/generate/task.ts, src/bin/methods/task/enqueue.ts
Better understanding the `commander.js` docs https://github.com/tj/commander.js#readme
=> Use [opt] to indicate optional CLI options and <opt> for required

package-lock.json, package.json
Reverts actionhero/actionhero#1681
=> Revert "Update deps"

README.md, package-lock.json, package.json
Typed breaking changes documented here https://github.com/TypeStrong/typedoc/releases/tag/v0.20.0
=> Update deps and use Typedoc v0.2

.github/workflows/test.yml, __tests__/core/process.ts, src/classes/process.ts
Now, `api.process.started<boolean>` can be checked to see if the server is fully booted and `api.process.stopped<boolean>` for when the server is totally done.
=> Add process.started and process.stopped indicators to the Actionhero Process

.github/workflows/test.yml
=> Test Node.js v12, v14, v16

src/initializers/chatRoom.ts
=> Log "ensuring the existence of the chatRoom" in debug level

src/modules/redis.ts
This most likely happens when shutting down the server, and you have an RPC call in progress
=> Prevent redis publish when disconnected

package-lock.json, package.json, src/classes/process/env.ts, src/classes/process/id.ts, src/modules/config.ts, src/modules/utils.ts, src/modules/utils/argv.ts
Closes https://github.com/actionhero/actionhero/issues/1907
=> Replace `optimist` with `yargs`

src/classes/process.ts
Rather than calling `process.exit` on a fatal error, Actionhero now throws.  This allows us to rely on the process listeners to decide what to do, if they are enabled.  
* No more duplicate "cannot shut down, actionhero is not running" messages if an initializer has a problem
* Allows jest to see the "throw" message and report it in tests if something goes wrong rather than a mysterious "process.exit) warning.
=> Better shutdown behavior

__tests__/servers/web/fileUpload.ts, src/modules/utils/isPlainObject.ts
See https://github.com/node-formidable/formidable/pull/796 for more info
=> Fix formidable logging error

src/config/logger.ts
Better types for the loggers we build in `/src/config/logger.ts`
=> Enhance Typing config in logger

src/classes/process/typescript.ts
Brings back some of the test detection from https://github.com/actionhero/actionhero/pull/2052, but in a safer way
=> Flag typescript=true if `TS_JEST` is present

src/bin/actionhero.ts, src/bin/methods/console.ts, src/bin/methods/generate.ts, src/bin/methods/generate/action.ts, src/bin/methods/generate/cli.ts, src/bin/methods/generate/initializer.ts, src/bin/methods/generate/plugin.ts, src/bin/methods/generate/server.ts, src/bin/methods/generate/task.ts, src/bin/methods/task/enqueue.ts, src/classes/cli.ts, src/classes/inputs.ts
Now CLI inputs can have a `formatter` and `validator` to check and format your inputs, just like Actions and Tasks
=> CLI inputs gain `formatter` and `validator`

src/actions/cacheTest.ts, src/actions/createChatRoom.ts, src/actions/sleepTest.ts, src/actions/validationTest.ts, src/bin/methods/generate/action.ts, src/bin/methods/generate/cli.ts, src/bin/methods/generate/initializer.ts, src/bin/methods/generate/plugin.ts, src/bin/methods/generate/server.ts, src/bin/methods/generate/task.ts, src/bin/methods/task/enqueue.ts, src/classes/inputs.ts
Requires we do `true as true` or `true as const` but it works if you do!
=> Improved ParamsFrom logic for required fields

src/modules/utils.ts, src/modules/utils/deepCopy.ts, src/modules/utils/filterObjectForLogging.ts, src/modules/utils/filterResponseForLogging.ts
Closes https://github.com/actionhero/actionhero/issues/2174
=> Deeply copy objects for logging

.github/workflows/publish_docs.yml, .github/workflows/test.yml
Stop testing on node 14, as it is in maintenance mode, and our browser tests no longer work
=> test with node 16, 18, and 20

package-lock.json, package.json
Reverts actionhero/actionhero#2527
=> Revert "Bump formidable and @types/formidable"

__tests__/core/cache.ts, src/actions/cacheTest.ts, src/modules/cache.ts
=> remove readAt and expireTimestamp from cache objects

package-lock.json, package.json
Reverts actionhero/actionhero#2550
=> Revert "Bump dot-prop from 6.0.1 to 8.0.2"
